//
// $Id: KContextMenu.tjs,v 1.5 2007/09/22 21:38:39 cvs Exp $
//


//----------------------------------------------------------------------
// ネイティブコンテキストメニュー
// KWindowのメニューを利用したコンテキストメニュークラス
//----------------------------------------------------------------------
class KNativeContextMenu extends KWindow
{
  // ルートアイテム
  var rootItem;
  // メニューを閉じた後、自動的にメニューをinvalidateするかどうか
  var toExit;

	//----------------------------------------------------------------------
	// 生成・破棄
	//----------------------------------------------------------------------
	function KNativeContextMenu(parentWindow = null, _toExit = true) {
		if (! k_kirikiriz)
			super.KWindow("", null, true);
		else if (parentWindow)
			super.KWindow(%[ customToolBar: void], parentWindow, true);
		else
			super.KWindow(%[ customToolBar: void], global.Window.mainWindow, true);
    toExit = _toExit;
    // 表示座標を得るために、プライマリレイヤをサイズ設定
    primaryLayer.setFixedSize(1, 1);
    // ルートアイテムを追加
    rootItem = new KMenuItem(this, "ルート");
    menu.add(rootItem);
	}

	//----------------------------------------------------------------------
	// 未定義関数は rootItem にフォワード
	//----------------------------------------------------------------------
	function missing(get_or_set, name, value) {
		if (! get_or_set
			&& rootItem !== void ) {
			if (typeof(rootItem[name]) != K_UNDEFINED) {
				*value = &rootItem[name];
				return true;
			}
		}
		return super.missing(...);
	}

	/**------------------------------
	 * メニュー表示
	 *
	 * 表示基準レイヤと基準座標を設定して呼び出すと、
	 * その位置にコンテキストメニューが開く。
	 *
	 * 指定を省略すると、カーソルの差している位置に開く。
	 *
	 * @param baseLayer 表示基準レイヤ
	 * @param x 表示基準X座標
	 * @param y 表示基準Y座標
	 ------------------------------*/
	function show(baseLayer = void, x = void, y = void) {
		// メニュー非選択時に onPopupHide が呼ばれるようにパラメータを設定
		stayOnTop = true;
		focusable = false;
		// ウィンドウが見えないように細工する
		borderStyle = bsNone;
		//    setMinSize(0, 0);
		//    setMaxSize(0, 0);
		setSize(0, 0);

		// 表示開始
		visible = true;
		// マウス位置を拾う
		var baseX, baseY;
		baseX = primaryLayer.cursorX;
		baseY = primaryLayer.cursorY;
		if (baseLayer) {
			baseX -= (baseLayer.cursorX - x) * baseLayer.window.zoomNumer / baseLayer.window.zoomDenom;
			baseY -= (baseLayer.cursorY - y) * baseLayer.window.zoomNumer / baseLayer.window.zoomDenom;
		}

		// ルートアイテムをマウス位置にポップアップ
		rootItem.popup(0,  baseX, baseY);
	}

	//----------------------------------------------------------------------
	// イベント処理
	//----------------------------------------------------------------------

	//------------------------------
	// メニューを閉じる
	//------------------------------
	function closeMenu {
		// 非表示に
		visible = false;
		// メニュー自体を消す
		if (toExit){
			onExit();
			invalidate(this);
		}
	}

	//------------------------------
	// メニュー非選択時、もしくは決定後別ウィンドウのフォーカス時に呼ばれる
	//------------------------------
	function onPopupHide {
		// ウィンドウを自動で閉じる
		closeMenu();
	}

	//------------------------------
	// 余分な処理を行わないためのダミー関数
	//------------------------------
	function invalidateLayout {
	}

	//------------------------------
	// 余分な処理を行わないためのダミー関数
	//------------------------------
	function onResize {
	}

	//------------------------------
	// 終了時コールバック
	//------------------------------
	function onExit {
	}
};


//----------------------------------------------------------------------
// コンテキストメニュー
//----------------------------------------------------------------------
class KContextMenu
{
	var entity;

	//----------------------------------------------------------------------
	// 生成・破棄
	//----------------------------------------------------------------------
	function KContextMenu(parentWindow = null, _toExit = true) {
		// グローバル設定により、ネイティブとカスタムのコンテキストメニューを使い分ける
		if (! useCustomMenu)
			entity = new KNativeContextMenu(...);
		else
			entity = new KCustomContextMenu(...);
		entity.onExit = onExit;
		Scripts.setCallMissing(this);
	}

	function finalize {
		invalidate entity;
	}

	//----------------------------------------------------------------------
	// 未定義関数は entity へフォワード
	//----------------------------------------------------------------------
	function missing(get_or_set, name, value) {
		if (! get_or_set) {
			if (typeof(entity[name]) != K_UNDEFINED) {
				*value = &entity[name];
				return true;
			}
		}
		return false;
	}

	//----------------------------------------------------------------------
	// 終了時コールバック
	//----------------------------------------------------------------------
	function onExit {
		invalidate this;
	}
}

//----------------------------------------------------------------------
// コンテキストメニューにカスタムメニューを使うかどうか
//----------------------------------------------------------------------
KContextMenu.useCustomMenu = false;
