// -*- coding: utf-16-le -*-


global.KCustomToolBarWidgetStyleDefinition =
	[
			%[ key: "captionId" ],
			%[ key: "buttonId" ],
			%[ key: "menuButtonId" ],
			%[ key: "closeButtonId" ]
	];

class KCustomToolBar extends KHorizontalBarLayout
{
	var menu;
	var menuInterface;
	var menuController;
	var _captionDrag = true;
	var useMenuButton = false;
	var useMenuBar = false;

	function KCustomToolBar(window, options = %[]) {
		var myOptions =
			%[
				style: %[
					isClass: %[
						KWidget: %[
							alignVertical: ALIGN_CENTER
						]
					]
				]
			];
		options = unionDictionary(options, myOptions, true);

		super.KHorizontalBarLayout(window, options);

		useMenuButton = getOption("useMenuButton", false);
		useMenuBar = getOption("useMenuBar", false);

		window.menu.visible = false;
		menu = new KCustomMenuItem(window, "root", "root");
		window.overrideMenu(menu);
		menuController = new KCustomMenuWindowController();

		var appIcon = getOption("appIcon", void);
		if (appIcon !== void)
			add(new KImageLabel(window, %[ icon : appIcon ]));
		if (useMenuButton)
			add(new KTextButton(window, %[ name: "_menu", label: "≡" ]));
		if (useMenuBar)
			add(new KCustomMenuBar(window, %[ name: "_menuBar",
											  controller: menuController,
											  rootMenuItem: menu ]));
		add(new global.KHorizontalBarLayout(window, %[ name: "_menuBar" ]));
		add(new global.KGridLayout(window, %[ name: "_captionLeftSideGrid", visible: false ]));
		add(new KTextLabel(window, %[ name: "_caption", marginalMaxWidth: K_WIDGET_MAX_POSSIBLE_WIDTH, style: %[ variable: true ] ]));
		add(new global.KGridLayout(window, %[ name: "_captionRightSideGrid", visible: false ]));
		add(new global.KGridLayout(window, %[ name: "_buttonGrid" ]));
		_buttonGrid.add(0, 0, new KTextButton(window, %[ name: "_minimize", label: "＿" ]));
		_buttonGrid.add(1, 0, new KTextButton(window, %[ name: "_maximize", label: "□" ]));
		_buttonGrid.add(2, 0, new KTextButton(window, %[ name: "_close", label: "×" ]));
		_caption.hitThreshold = 256;

		window.overrideCaption(&(_caption.label));


//		menu = new KCustomMenuItem(window, "root", "root");
//		menuInterface = new KCustomToolBarMenuInterface(this, menu);
//		window.overrideMenu(menuInterface);
	}

	function finalize {
		invalidate menuController;
		super.finalize();
	}

	property widgetStyleDefinition {
		getter {
			return concatArray(super.widgetStyleDefinition, KCustomToolBarWidgetStyleDefinition);
		}
	}

	property captionLeftSideGrid {
		getter {
			return _captionLeftSideGrid;
		}
	}

	property captionRightSideGrid {
		getter {
			return _captionRightSideGrid;
		}
	}

	property captionDrag {
		getter {
			return _captionDrag;
		}
		setter(v) {
			_captionDrag = v;
			invalidateCaptionDrag();
		}
	}

	property caption {
		getter {
			return _caption;
		}
	}

	property menuButton {
		getter {
			return _menu;
		}
	}

	property maximizeButton {
		getter {
			return _maximize;
		}
	}

	property minimizeButton {
		getter {
			return _minimize;
		}
	}

	property closeButton {
		getter {
			return _close;
		}
	}

	function onAddMenuItem(menuItem) {
		var label = new KCustomToolBarMenuLabel(window,
												%[ label: menuItem.caption,
												   menuItem: menuItem,
												   style: %[ marginHorizontal: 10 ],
												 ]);
		_menuBar.add(label);
	}

	function onChildValueModified(child) {
		switch (child.name) {
		case "_minimize": window.minimize(); break;
		case "_maximize": window.maximized ? window.showRestore() : window.maximize(); break;
		case "_close": window.pushClose(); break;
		case "_menu": menuController.popupRootMenu(_menu.screenRect, menu, window); break;
		}
	}

	function onDrawContents() {
		if (useMenuButton)
			_menu.id = widgetStyle.menuButtonId;
		_caption.id = widgetStyle.captionId;
		_minimize.id = widgetStyle.buttonId;
		_maximize.id = widgetStyle.buttonId;
		_close.id = widgetStyle.closeButtonId;
		super.onDrawContents();
	}

	function onLocateLayout() {
		super.onLocateLayout();
		invalidateCaptionDrag();
	}

	function invalidateCaptionDrag {
		if (_captionDrag)
			window.setCaptionRect(_caption.left, 0, _caption.width, height);
		else
			window.setCaptionRect(0, 0, 0, 0);
	}

	function onWindowActivate {
		addCustomStyleState("windowActive");
	}

	function onWindowDeactivate {
		removeCustomStyleState("windowActive");
		menuController.clearMenuWindows();
	}
};
