global.k_kirikiriz = (typeof(System.exeBits) != "undefined");

if (! k_kirikiriz) {
	if (Storages.isExistentStorage(System.exePath + "kwidgets.xp3"))
		Storages.addAutoPath(System.exePath + "kwidgets.xp3>plugin/");
	else
		Storages.addAutoPath("kwidgets/plugin/");
} else {
	if (Storages.isExistentStorage(System.exePath + "kwidgets.xp3")) {
		switch (System.exeBits) {
		case 32: Storages.addAutoPath(System.exePath + "kwidgets.xp3>plugin/"); break;
		case 64: Storages.addAutoPath(System.exePath + "kwidgets.xp3>plugin64/"); break;
		}
	} else {
		switch (System.exeBits) {
		case 32: Storages.addAutoPath("kwidgets/plugin/"); break;
		case 64: Storages.addAutoPath("kwidgets/plugin64/"); break;
		}
	}
}

if (k_kirikiriz) {
	if (typeof(Debug["console"]) === "undefined") {
		Plugins.link("menu.dll");
		global.Pad = %[];
		Debug.console = %[];
	}
}

Plugins.link("ksupport.dll");
Plugins.link("windowEx.dll");
Plugins.link("LayerExScreen.dll");
Scripts.execStorage("KDefs.tjs");
Scripts.execStorage("KUtils.tjs");
Scripts.execStorage("KStyle.tjs");
Scripts.execStorage("KWindow.tjs");
Scripts.execStorage("KPersistentDictionary.tjs");
Scripts.execStorage("KWidget.tjs");
Scripts.execStorage("KEntity.tjs");
Scripts.execStorage("KLayout.tjs");
Scripts.execStorage("KRangePointer.tjs");
Scripts.execStorage("KPrimaryWidget.tjs");
Scripts.execStorage("KPrimitiveIcon.tjs");
Scripts.execStorage("KVirtualWidget.tjs");
Scripts.execStorage("KStatusBar.tjs");
Scripts.execStorage("KSpacer.tjs");
Scripts.execStorage("KSeparator.tjs");
Scripts.execStorage("KWindowResizeHandle.tjs");
Scripts.execStorage("KLabel.tjs");
Scripts.execStorage("KButton.tjs");
Scripts.execStorage("KToggleButton.tjs");
Scripts.execStorage("KCheckBox.tjs");
Scripts.execStorage("KRadioButton.tjs");
Scripts.execStorage("KComboBox.tjs");
Scripts.execStorage("KSlider.tjs");
Scripts.execStorage("KTextInput.tjs");
Scripts.execStorage("KTextInputSlider.tjs");
Scripts.execStorage("KTextEdit.tjs");
Scripts.execStorage("KTagTextEdit.tjs");
Scripts.execStorage("KGridLayout.tjs");
Scripts.execStorage("KCustomToolBar.tjs");
Scripts.execStorage("KRadioLayout.tjs");
Scripts.execStorage("KAbsoluteLayout.tjs");
Scripts.execStorage("KRelativeLayout.tjs");
Scripts.execStorage("KScrollLayout.tjs");
Scripts.execStorage("KMenu.tjs");
Scripts.execStorage("KCustomMenu.tjs");
Scripts.execStorage("KContextMenu.tjs");
Scripts.execStorage("KList.tjs");
Scripts.execStorage("KFrameLayout.tjs");
Scripts.execStorage("KTabLayout.tjs");
Scripts.execStorage("KSpliterLayout.tjs");
Scripts.execStorage("KSpiralLayout.tjs");
Scripts.execStorage("KFixedSizeLayout.tjs");
Scripts.execStorage("KColorBox.tjs");
Scripts.execStorage("KColorPickerDialog.tjs");
Scripts.execStorage("KTimeLineControl.tjs");
Scripts.execStorage("KCustomUI.tjs");
Scripts.execStorage("KCustomDialog.tjs");
Scripts.execStorage("KTable.tjs");
Scripts.execStorage("KTextBoard.tjs");
Scripts.execStorage("KSizeLimitLayout.tjs");
Scripts.execStorage("KStringFormat.tjs");
Scripts.execStorage("KMarkdown.tjs");
Scripts.execStorage("KFloaterLayout.tjs");

// デフォルトスタイルをロードする
styleRepository.loadStylesStorage("KDefaultStyle.tjs");

// マウスホイールはメッセージで取得
// (DirectInput経由で取得するとたまにバグって吉里吉里が応答しなくなるのでその対策)
System.setArgument('-wheel', 'message');

