/**----------------------------------------------------------------------
 * タイムラインアイテム
 ----------------------------------------------------------------------*/
class KTimeLineItem extends KListItem
{
	// フレーム配列
	var _frameList;
	// シングルフレーム描画色
	var _singleFrameColor = void;
	// 連続フレーム描画色
	var _continuousFrameColor = void;
	// 補完フレーム描画色
	var _tweenFrameColor = void;
	// 選択範囲
	var selection = [];
	// マーカーマスク
	var markerMask = TIMELINE_MARKER_MASK_LEFT;
	// 範囲選択対応
	var supportSelection = true;
	// 連続フレームを補完フレームとして扱う
	var forceTweenFrame = false;

	/**------------------------------
	 * コンストラクタ
	 *
	 * @param label ラベル
	 * @param name 名前
	 *
	 * タイムラインアイテムを作成する。
	 *
	 * KTimeLineItem は KListItem を拡張したクラスで、
	 * リストアイテムの全ての動作に加え、タイムラインごとのフレーム情報を
	 * 管理する機能を持っている。
	 *
	 * フレームは time, type, content の4つのフィールドを持つ
	 * オブジェクトとして定義される。timeはフレームの開始時間、
	 * content はユーザー定義のフレーム情報となる。
	 * type はフレームの種別。以下の4種類のどれかとなる
	 * - TIMELINE_FRAME_TYPE_NULL ヌルフレーム。フレームが存在しない領域として扱われる
	 * - TIMELINE_FRAME_TYPE_SINGLE シングルフレーム。1単位だけ占有する連続しないフレーム
	 * - TIMELINE_FRAME_TYPE_CONTINUOUS  連続フレーム。次のフレームまで連続する領域を占有するフレーム。
	 * - TIMELINE_FRAME_TYPE_TWEEN 連続補完フレーム。次のフレームまで連続する領域を補完しながらつなぐフレーム。
	 *
	 * 既存のフレームを参照するには以下の関数群を使う。
	 * 参照したフレームの内容を直接書き換えることでフレーム情報を上書き出来るが、
	 * フレームオブジェクトはフレーム操作によって頻繁に更新されるので、
	 * 参照したフレームを長時間に渡って参照し続ける事は推奨しない。
	 * 編集する都度、参照するべきである。
	 *
	 * - frameCount フレーム数を参照する
	 * - frameAt(index) フレームを参照する
	 * - frameLengthAt(index) フレームの長さを参照する
	 * - findFrame(time) 時間に対応したフレームのインデックスを得る。
	 * - lastTime 末尾のフレームの時間を得る
	 * - getCompleteFrameContent(time) 時間に対応したフレーム情報を計算する
	 *
	 * フレームを操作するには以下のフレーム操作関数群を使う。
	 *
	 * - insertKeyFrame(time, type) キーフレームを挿入する。
	 * - deleteKeyFrame(time)       キーフレームを削除する。
	 * - splitFrame(time)           フレームを分割する。
	 * - deleteAllFrame()           全てのフレームを削除する。
	 *
	 * 特定区間のフレームをコピ、ペーストするには以下の関数群を使う
	 *
	 * - copyFrameRange(beginTime, endTime) フレームをコピーする
	 * - cutFrameRange(beginTime, endTime)  フレームをカットする
	 * - pasteFrame(time, frameList)        フレームをペーストする
	 *
	 * フレーム操作関数を呼ぶと、必要に応じて以下の関数群が内部的に
	 * 呼び出される。ユーザーは、適切にこれらの関数を実装しておく必要がある。
	 *
	 * - tweenFrameContent(fromContent, toContent, ratio) フレーム間の補完を行う。
	 *
	 * フレームの補完計算を行うために以下の補完関数が用意されている。
	 *
	 * - tweenIntValue(fromValue, toValue, ratio) 整数をリニアに補完する
	 *
	 * また、フレームの見た目や挙動を設定する以下のプロパティ群が存在する。
	 *
	 * - singleFrameColor シングルフレームのBGカラーを設定する
	 * - continuousFrameColor 連続フレームのBGカラーを設定する
	 * - tweenFrameColor     補完フレームのBGカラーを設定する
	 *
	 * フレーム情報を変更したなどの理由でフレームの再描画が必要な時は以下の関数群を使う。
	 *
	 * - redrawFrameRange(fromTime, toTime) 指定範囲のフレームを再描画する。
	 * - redrawAllFrame() 全てのフレームを再描画する。
	 *
	 * 標準で、以下のシリアライズ関数を持つ。
	 *
	 * - serialize() アイテムの内容をオブジェクトにシリアライズする。
	 * - unserialize(data) オブジェクトの内容をアンシリアライズする。
	 *
	 * また、特定のタイミングで以下のイベント関数が呼び出される
	 *
	 * - onTimeLineRightClick(time) タイムラインが右クリックされると呼び出される。
	 * - onTimeLineKeyDown(key, shift) タイムライン上でキーが押されると呼び出される。
	 * - onFrameDragged() フレームがドラッグされた
	 ------------------------------*/
	function KTimeLineItem() {
		super.KListItem(...);
		frameList = [];
	}

	property owner {
		getter {
			return root.owner;
		}
	}

	property view {
		getter {
			return root.owner._layerView;
		}
	}

	property TIMELINE_FRAME_WIDTH {
		getter {
			return root.TIMELINE_FRAME_WIDTH;
		}
	}

	property TIMELINE_FRAME_HEIGHT {
		getter {
			return view.TIMELINE_FRAME_HEIGHT;
		}
	}

	property inArea {
		getter {
			return view.isItemInArea(this);
		}
	}

	/**------------------------------
	 * フレームリスト
	 *
	 * @return フレームリスト
	 ------------------------------*/
	property frameList {
		getter {
			return _frameList;
		}
		setter (v) {
			_frameList = v;
			selection.reject(_frameList, function(elm, frameList) { return elm >= frameList.count || frameList[elm].type == TIMELINE_FRAME_TYPE_NULL; });
		}
	}

	/**------------------------------
	 * フレーム数をカウントする
	 *
	 * @return フレーム数
	 ------------------------------*/
	property frameCount {
		getter {
			return frameList.count;
		}
	}

	/**------------------------------
	 * フレームを参照する
	 *
	 * @param index インデックス
	 *
	 * インデックスに対応するフレームを返す。
	 * インデックスが無効な場合はvoidを返す。
	 ------------------------------*/
	function frameAt(index) {
		if (index < 0
			|| index >= frameList.count)
			return void;
		else
			return frameList[index];
	}


	/*------------------------------
	 * タイムラインが空かどうか判定する
	 ------------------------------*/
	property isEmpty {
		getter {
			return frameList.count == 0;
		}
	}

	/**------------------------------
	 * 時間を対応してフレームを検索する
	 *
	 * @param time 時間
	 * @param includeTail ラストフレーム以降の末尾のスペースを含めて検索するかどうか
	 * @return インデックス
	 *
	 * 時間に対応するフレームのインデックスを返す。
	 * フレームが見つからなかった時は-1を返す。
	 ------------------------------*/
	function findFrame(time, includeTail = false) {
		return timeline_find_frame(this.frameList, time, includeTail);

		// C++プラグインのリファレンス実装
		var begin, end, mid;
		begin = 0; end = frameList.count;

		// 末尾だけ特殊処理
		if (end) {
			if (! includeTail) {
				if (frameList[end - 1].time == time)
					return end - 1;
				if (frameList[end - 1].time < time)
					return -1;
			} else {
				if (frameList[end - 1].time <= time)
					return end - 1;
			}
		}

		// 二分検索
		while (begin < end) {
			mid = int((begin + end) / 2);
			var frame = frameList[mid];
			var nextFrame = frameList[mid + 1];
			if (frame.time <= time && time < nextFrame.time)
				return mid;
			if (time < frame.time)
				end = mid;
			else
				begin = mid + 1;
		}
		return -1;
	}

	/**------------------------------
	 * 末尾のフレームの終端時間を得る
	 *
	 * @return 終端時間
	 *
	 * フレームが存在しない場合-1を返す
	 ------------------------------*/
	property lastTime {
		getter {
			if (frameList.count) {
				if (frameList[-1].type == TIMELINE_FRAME_TYPE_NULL)
					return frameList[-1].time - 1;
				else
					return frameList[-1].time;
			} else
				return -1;
		}
	}

	/**------------------------------
	 * フレームの長さを取得する
	 *
	 * @param index インデックス
	 ------------------------------*/
	function frameLengthAt(index) {
		if (index < frameList.count - 1)
			return frameList[index + 1].time - frameList[index].time;
		else {
			var frame = frameList[index - 1];
			var loopEndTime = root.owner.loopEndTime;
			if (loopEndTime >= 0
				&& loopEndTime > frame.time )
				return loopEndTime - frame.time;
			else
				return 0;
		}
	}

	/**------------------------------
	 * フレームの右側の時間をを取得する
	 *
	 * @param index インデックス
	 ------------------------------*/
	function frameRightTimeAt(index) {
		if (index < frameList.count - 1)
			return frameList[index].time - 1;
		else
			return void;
	}

	/**------------------------------
	 * 時間に対応したフレーム情報を計算する
	 *
	 * @param time 時間
	 * @return フレーム情報
	 *
	 * 時間に対応したフレーム情報を計算して返す。
	 * 補完可能なトゥイーンフレームがあれば、トゥイーンを済ませたフレーム情報を返す。
	 * 補完可能なフレームが無ければキーフレームのフレーム情報をそのまま返す。
	 * 指定ポイントにフレームが無ければvoidを返す
	 ------------------------------*/
	function getCompleteFrameContent(time) {
		var frameIndex = findFrame(time);
		if (frameIndex < 0) {
			return void;
		}
		var frame = frameAt(frameIndex);
		switch (frame.type) {
		case TIMELINE_FRAME_TYPE_NULL:
			return void;
		case TIMELINE_FRAME_TYPE_SINGLE:
			if (frame.time == time)
				return frame.content;
			else
				return void;
		case TIMELINE_FRAME_TYPE_CONTINUOUS:
			if (! forceTweenFrame)
				return frame.content;
		case TIMELINE_FRAME_TYPE_TWEEN:
			var nextFrame = frameAt(frameIndex + 1);
			if (nextFrame.type == TIMELINE_FRAME_TYPE_NULL) {
				var loopBeginTime = root.owner.loopBeginTime;
				var loopEndTime = root.owner.loopEndTime;
				if (loopEndTime == nextFrame.time
					&& loopBeginTime < frame.time
					&& findFrame(loopBeginTime) >= 0
					&& frameAt(findFrame(loopBeginTime)).type != TIMELINE_FRAME_TYPE_NULL) {
					nextFrame = createNewFrame(root.owner.loopEndTime, TIMELINE_FRAME_TYPE_CONTINUOUS, getCompleteFrameContent(loopBeginTime));
				}
			}
			if (nextFrame !== void
				&& nextFrame.type !== TIMELINE_FRAME_TYPE_NULL)
				return tweenFrameContent(frame.content,
										 nextFrame.content,
										 (time - frame.time)
										 / (nextFrame.time - frame.time));
			else
				return frame.content;
		}
	}

	/**------------------------------
	 * フレームの挿入
	 *
	 * @param time 時間
	 * @param type タイプ
	 * @param content 初期コンテント。
	 *
	 * 新規フレームを挿入する。
	 *
	 * 指定箇所に既存のフレームがある場合は上書きする。
	 * 空フレームの場合は content を明示的に指定してやる。
	 ------------------------------*/
	function insertKeyFrame(time, type, content = void, doInvalidate = true) {
		var frameIndex = findFrame(time, true);
		var frame = frameAt(frameIndex);

		if (owner.keyframePriorSideLeft) {
			if (frame !== void
				&& frame.time == time) {
				frameList.erase(frameIndex);
				correctSelectionByRemoveIndex(frameIndex);
				frameIndex--;
			} else if (frame !== void
					   && frameIndex == frameList.count - 1
					   && frame.type == TIMELINE_FRAME_TYPE_NULL) {
				frameList.erase(frameIndex);
				frameIndex--;
			}

			var newFrame;
			if (type == TIMELINE_FRAME_TYPE_NULL)
				newFrame = createNewFrame(time, type, void);
			else
				newFrame = createNewFrame(time, type, content);

			frameList.insert(frameIndex + 1, newFrame);
			correctSelectionByInsertIndex(frameIndex);
			if (doInvalidate)
				invalidateNullFrame();
		}
		else if (owner.keyframePriorSideRight) {
			var frameRightTime = frameRightTimeAt(frameIndex);
			if (frame !== void
				&& frameRightTime === time) {
				frame.type = type;
				frame.content = type == TIMELINE_FRAME_TYPE_NULL ? void : content;
			} else if (frame !== void) {
				var newFrame = createNewFrame(frame.time, type, content);
				frame.time = time + 1;

				frameList.insert(frameIndex, newFrame);
				correctSelectionByInsertIndex(frameIndex + 1);
				if (doInvalidate)
					invalidateNullFrame();
			} else {
				var newFrame = createNewFrame(0, type, content);
				frameList.insert(0, newFrame);
				if (frameList.count == 1
					|| frameList[1].time != time + 1)
					frameList.insert(1, createNewFrame(time + 1, TIMELINE_FRAME_TYPE_NULL, void));
				if (doInvalidate)
					invalidateNullFrame();
			}
		}
	}

	/**------------------------------
	 * フレームの削除
	 *
	 * @param time 時間
	 *
	 * 指定箇所にあるフレームを削除する。
	 * 指定箇所にフレームが無い場合は何もしない。
	 ------------------------------*/
	function deleteKeyFrame(time) {
		var frameIndex = findFrame(time);
		if (frameIndex < 0)
			return;
		deleteKeyFrameAt(frameIndex);
	}

	function deleteKeyFrameAt(frameIndex) {
		frameList[frameIndex].content = void;
		frameList[frameIndex].type = TIMELINE_FRAME_TYPE_NULL;
		invalidateNullFrame();
		root.owner.onRenderFrame();
	}

	/**------------------------------
	 * 全てのフレームを削除する
	 ------------------------------*/
	function deleteAllFrame {
		frameList = [];
		selection = [];
		redrawAllFrame();
		root.owner.onRenderFrame();
	}

	/**------------------------------
	 * フレームを分割する
	 *
	 * @param time 時間
	 *
	 * フレームを指定時間で分割します。
	 *
	 * 分割の対象になるのは連続フレーム、もしくは補完フレームです。
	 *
	 * 末尾で他のフレームと隣接している補完フレームは、
	 * splitTweenFrame()関数を使って分割される。
	 * それ以外のフレームは splitContinuousFrame()関数を使って分割される。
	 ------------------------------*/
	function splitFrame(time) {
		if (! (pointEffectiveFrame && ! pointFrameHead))
			return;

		var frameIndex = findFrame(time);
		var frame = frameAt(frameIndex);
		if (frame.type == TIMELINE_FRAME_TYPE_SINGLE)
			return;

		if (owner.keyframePriorSideRight)
			time++;

		var newFrames;
		if (frame.type == TIMELINE_FRAME_TYPE_TWEEN
			|| (forceTweenFrame && frame.type == TIMELINE_FRAME_TYPE_CONTINUOUS)) {
			if (owner.keyframePriorSideLeft) {
				var nextFrame = frameAt(frameIndex + 1);
				if (nextFrame === void
					|| frameIndex == frameCount - 2) {
					var loopBeginTime = root.owner.loopBeginTime;
					var loopEndTime = root.owner.loopEndTime;
					if (loopBeginTime >= 0
						&& loopEndTime > frame.time
						&& loopBeginTime < frame.time
						&& findFrame(loopBeginTime) >= 0
						&& frameAt(findFrame(loopBeginTime)).type != TIMELINE_FRAME_TYPE_NULL) {
						nextFrame = createNewFrame(root.owner.loopEndTime, TIMELINE_FRAME_TYPE_CONTINUOUS, getCompleteFrameContent(loopBeginTime));
					}
				}
				if (nextFrame !== void
					&& nextFrame.type != TIMELINE_FRAME_TYPE_NULL)
					newFrames = splitTweenFrame(frame, nextFrame, time);
				else
					newFrames = splitContinuousFrame(frame, time);
			} else if (owner.keyframePriorSideRight) {
				var length = frameLengthAt(frameIndex);
				var prevFrame = frameAt(frameIndex - 1);
				if (prevFrame !== void
					&& prevFrame.type != TIMELINE_FRAME_TYPE_NULL)
					newFrames = splitTweenFrameRight(prevFrame, frame, time, length);
				else
					newFrames = splitContinuousFrame(frame, time);
			}
		} else
			newFrames = splitContinuousFrame(frame, time);
		frameList[frameIndex] = newFrames[0];
		frameList.insert(frameIndex + 1, newFrames[1]);
		redrawAllFrame();
		root.owner.onRenderFrame();
	}

	/**------------------------------
	 *  フレーム情報を補完する
	 *
	 * @param  fromContent 補完元フレーム情報
	 * @param  toContent 補完先フレーム情報
	 * @param  ratio 比率 (0.0〜1.0)
	 * @return 補完済みフレーム情報
	 *
	 * フレーム情報を補完して、新たなフレーム情報を返す。
	 *
	 * フレーム情報はユーザー定義の任意のデータなので、
	 * 派生クラスで必要に応じて適切に実装する必要がある。
	 *
	 * デフォルト実装ではvoidを返す。
	 ------------------------------*/
	function tweenFrameContent(fromContent, toContent, ratio) {
		return void;
	}

	/**------------------------------
	 * シングルフレームカラー
	 *
	 * @param v シングルフレームカラー
	 * @return シングルフレームカラー
	 *
	 * シングルフレームのカラーを設定する
	 ------------------------------*/
	property singleFrameColor {
		getter {
			if (_singleFrameColor === void)
				return view.singleFrameColor;
			else
				return _singleFrameColor;
		}
		setter(v) {
			_singleFrameColor = v;
		}
	}

	property singleFrameLeftColor {
		getter {
			var v = singleFrameColor;
			return (v instanceof "Array") ? v[0] : v;
		}
	}

	property singleFrameRightColor {
		getter {
			var v = singleFrameColor;
			return (v instanceof "Array") ? v[1] : v;
		}
	}

	/**------------------------------
	 *  連続フレームカラー
	 *
	 * @param v 連続フレームカラー
	 * @return 連続フレームカラー
	 *
	 * 連続フレームのカラーを設定する
	 ------------------------------*/
	property continuousFrameColor {
		getter {
			if (_continuousFrameColor === void)
				return view.continuousFrameColor;
			else
				return _continuousFrameColor;
		}
		setter(v) {
			_continuousFrameColor = v;
		}
	}

	property continuousFrameLeftColor {
		getter {
			var v = continuousFrameColor;
			return (v instanceof "Array") ? v[0] : v;
		}
	}

	property continuousFrameRightColor {
		getter {
			var v = continuousFrameColor;
			return (v instanceof "Array") ? v[1] : v;
		}
	}

	/**------------------------------
	 *  補完フレームカラー
	 *
	 * @param v 補完フレームカラー
	 * @return 補完フレームカラー
	 *
	 * 補完フレームのカラーを設定する
	 ------------------------------*/
	property tweenFrameColor {
		getter {
			if (_tweenFrameColor === void)
				return view.tweenFrameColor;
			else
				return _tweenFrameColor;
		}
		setter(v) {
			_tweenFrameColor = v;
		}
	}

	property tweenFrameLeftColor {
		getter {
			var v = tweenFrameColor;
			return (v instanceof "Array") ? v[0] : v;
		}
	}

	property tweenFrameRightColor {
		getter {
			var v = tweenFrameColor;
			return (v instanceof "Array") ? v[1] : v;
		}
	}

	function redraw() {
		super.redraw();
		if (itemVisible)
			redrawAllFrame();
	}

	/**------------------------------
	 * フレームを再描画する
	 *
	 * @param frameIndex インデックス
	 * @param toTime 終点
	 ------------------------------*/
	function redrawFrame(frameIndex) {
		if (visible) {
			if (frameIndex + 1 >= frameList.count)
				return;
			var frame = frameAt(frameIndex);
			var nextFrame = frameAt(frameIndex + 1);
			root.owner._layerView.redrawRect(frame.time * TIMELINE_FRAME_WIDTH, top, (nextFrame.time - frame.time) * TIMELINE_FRAME_WIDTH, height);
		}
	}

	/**------------------------------
	 * フレームを再描画する
	 *
	 * @param fromTime 始点
	 * @param toTime 終点
	 ------------------------------*/
	function redrawFrameRange(fromTime, toTime) {
		if (visible)
			root.owner._layerView.redrawRect(fromTime * TIMELINE_FRAME_WIDTH, top, (toTime - fromTime + 1) * TIMELINE_FRAME_WIDTH, height);
	}

	/**------------------------------
	 * 全フレームを再描画する
	 ------------------------------*/
	function redrawAllFrame {
		redrawFrameRange(0, Math.ceil(root.owner._layerView.width / TIMELINE_FRAME_WIDTH));
	}

	/**------------------------------
	 * シリアライズ
	 *
	 * @return シリアライズしたオブジェクト
	 *
	 * アイテムの内容をシリアライズする。
	 ------------------------------*/
	function serialize {
		var data = %[ className: className,
					  label:label,
					  name:name,
					  frameList: duplicateStruct(frameList),
					  childList: [] ];
		for (var i = 0; i < childCount; i++)
			data.childList.add(childAt(i).serialize());
		return data;
	}

	/**------------------------------
	 * アンシリアライズ
	 *
	 * @param data シリアライズしたオブジェクト
	 *
	 * アイテムの内容をアンシリアライズする。
	 * シリアライズした内容に子レイヤが含まれていたら、自動的に子レイヤも復元する。
	 ------------------------------*/
	function unserialize(data) {
		var prevLastTime = lastTime;
		label = data.label;
		name = data.name;
		frameList = duplicateStruct(data.frameList);
		for (var i = 0; i < data.childList.count; i++) {
			var child = new global[data.childList[i].className](data.childList[i].label,
																data.childList[i].name);
			child.unserialize(data.childList[i]);
			add(child);
		}
		if (root !== void) {
			redrawFrameRange(0, Math.max(lastTime, prevLastTime));
			root.owner.onRenderFrame();
		}
	}

	/**------------------------------
	 * フレームの先頭を指している
	 ------------------------------*/
	property pointFrameHead {
		getter {
			var frameIndex = findFrame(owner.selectedTime);
			if (frameIndex >= 0) {
				var frame = frameAt(frameIndex);
				if (owner.keyframePriorSideLeft)
					return frame.time == owner.selectedTime;
				else if (owner.keyframePriorSideRight)
					return frame.time + frameLengthAt(frameIndex) -1 == owner.selectedTime;
			}
			return false;
		}
	}

	/**------------------------------
	 * 有効なフレームを指している
	 ------------------------------*/
	property pointEffectiveFrame {
		getter {
			var frameIndex = findFrame(owner.selectedTime);
			if (frameIndex >= 0) {
				var frame = frameAt(frameIndex);
				return frame.type != TIMELINE_FRAME_TYPE_NULL;
			}
			return false;
		}
	}

	/**------------------------------
	 * 有効なフレームの先頭を指している
	 ------------------------------*/
	property pointEffectiveFrameHead {
		getter {
			var frameIndex = findFrame(owner.selectedTime);
			if (frameIndex >= 0) {
				var frame = frameAt(frameIndex);
				if (frame.type != TIMELINE_FRAME_TYPE_NULL) {
					if (owner.keyframePriorSideLeft)
						return frame.time == owner.selectedTime;
					else if (owner.keyframePriorSideRight)
						return frame.time + frameLengthAt(frameIndex) - 1 == owner.selectedTime;
				}
			}
			return false;
		}
	}

	/**------------------------------
	 * フレームリストを更新する
	 ------------------------------*/
	function updateFrameList(newFrameList) {
		var prevLastTime = lastTime;
		frameList = duplicateStruct(newFrameList);
		redrawFrameRange(0, Math.max(lastTime, prevLastTime));
		if (root !== void)
			root.owner.onRenderFrame();
	}

	/**------------------------------
	 * 指定の範囲のフレーム情報をコピーする
	 *
	 * @param beginTime 開始時間
	 * @param endTime   終端時間
	 * @return コピーしたフレーム情報
	 ------------------------------*/
	function copyFrameRange(beginTime, endTime) {
		var result = [];
		for (var i = 0; i < frameList.count; i++) {
			var frame = frameList[i];
			if (beginTime <= frame.time
				&& frame.time < endTime) {
				var copyFrame = duplicateStruct(frame);
				copyFrame.time -= beginTime;
				result.add(copyFrame);
			}
		}
		return result;
	}

	function copyFrameRangeRight(beginTime, endTime) {
		var result = [];
		for (var i = 0; i < frameList.count - 1; i++) {
			var frame = frameList[i];
			var nextFrame = frameList[i + 1];
			var time = nextFrame.time - 1;
			if (beginTime <= time
				&& time < endTime) {
				var copyFrame = duplicateStruct(frame);
				copyFrame.time = nextFrame.time - 1 - beginTime;
				result.add(copyFrame);
			}
		}
		return result;
	}

	/**------------------------------
	 * 指定の範囲のフレーム情報をカットする
	 *
	 * @param beginTime 開始時間
	 * @param endTime   終端時間
	 * @return カットしたフレーム情報
	 ------------------------------*/
	function cutFrameRange(beginTime, endTime) {
		var result = copyFrameRange(beginTime, endTime);
		// 範囲内にあるフレームをひとまず削除
		for (var i = 0; i < frameList.count; i++) {
			var frame = frameList[i];
			if (beginTime <= frame.time
				&& frame.time < endTime) {
				frameList.erase(i);
				i--;
			}
		}
		invalidateNullFrame();
		return result;
	}

	function cutFrameRangeRight(beginTime, endTime) {
		var result = copyFrameRangeRight(beginTime, endTime);
		// 範囲内にあるフレームをひとまず削除
		for (var i = 0; i < frameList.count - 1; i++) {
			var frame = frameList[i];
			var nextFrame = frameList[i + 1];
			var time = nextFrame.time - 1;
			if (beginTime <= time
				&& time < endTime) {
				frameList.erase(i);
				i--;
			}
		}
		invalidateNullFrame();
		return result;
	}

	/**------------------------------
	 * コピーしたフレーム情報をペーストする
	 *
	 * @param time ペーストする時間
	 * @param frameList コピーしたフレーム情報
	 ------------------------------*/
	function pasteFrame(time, copyFrameList) {
		// リストが空ならそのまま。
		if (copyFrameList.count == 0)
			return;
		var beginTime, endTime;
		beginTime = time + copyFrameList[0].time;
		endTime = time + copyFrameList[-1].time + 1;
		// 範囲内にあるフレームをひとまず削除
		for (var i = 0; i < frameList.count; i++) {
			var frame = frameList[i];
			if (beginTime <= frame.time
				&& frame.time < endTime) {
				frameList.erase(i);
				i--;
			}
		}
		// 挿入可能位置にフレームを全て挿入
		var insertIndex;
		for (insertIndex = 0; insertIndex < frameList.count; insertIndex++)
			if (frameList[insertIndex].time >= endTime)
				break;
		for (var i = 0; i < copyFrameList.count; i++) {
			var item = duplicateStruct(copyFrameList[i]);
			item.time += time;
			frameList.insert(insertIndex + i, item);
		}
		invalidateNullFrame();
	}

	function pasteFrameRight(time, copyFrameList) {
		// リストが空ならそのまま。
		if (copyFrameList.count == 0)
			return;
		var beginTime, endTime;
		beginTime = time + copyFrameList[0].time;
		endTime = time + copyFrameList[-1].time + 1;
		// 範囲内にあるフレームをひとまず削除
		for (var i = 0; i < frameList.count - 1; i++) {
			var nextFrame = frameList[i];
			var time = nextFrame.time - 1;
			if (beginTime <= time
				&& time < endTime) {
				frameList.erase(i);
				i--;
			}
		}
		// 挿入可能位置にフレームを全て挿入
		var insertIndex;
		for (var i = 0; i < copyFrameList.count; i++) {
			var frame = copyFrameList[i];
			insertKeyFrame(time + frame.time, frame.type, frame.content);
		}
	}

	/*------------------------------
	 * エリア内のフレームをコピーする
	 ------------------------------*/
	function copyFramesByArea(beginTime, endTime) {
		if (! supportSelection
			|| ! view.isItemInArea(this))
			return [];
		var range = copyFrameRange(beginTime, endTime);
		for (var i = 0; i < range.count - 1; i++) {
			range[i].length = range[i + 1].time - range[i].time;
		}
		return range;
	}

	/*------------------------------
	 * 選択範囲のフレームをコピーする
	 ------------------------------*/
	function copyFramesBySelection(beginTime) {
		return selection._map(beginTime, function(i, beginTime) {
			var frame = duplicateStruct(frameList[i]);
			frame.length = frameList[i + 1].time - frame.time;
			frame.time -= beginTime;
			return frame;
		} incontextof(this) );
	}

	/*------------------------------
	 * フレームをコピーする
	 ------------------------------*/
	function copyFrames(beginTime, endTime) {
		if (owner.selectionModeFrameEnabled) {
			if (owner.hasSelection)
				return copyFramesBySelection(...);
			else
				return copyFramesByArea(...);
		} else if (owner.selectionModeAreaEnabled) {
			if (! supportSelection
				|| ! view.isItemInArea(this))
				return [];
			if (owner.keyframePriorSideLeft)
				return copyFrameRange(...);
			else if (owner.keyframePriorSideRight)
				return copyFrameRangeRight(...);
		}
	}

	/*------------------------------
	 * エリア内のフレームをカットーする
	 ------------------------------*/
	function cutFramesByArea(beginTime, endTime) {
		if (! supportSelection
			|| ! view.isItemInArea(this))
			return [];
		var range = cutFrameRange(beginTime, endTime);
		for (var i = 0; i < range.count - 1; i++) {
			range[i].length = range[i + 1].time - range[i].time;
		}
		return range;
	}

	/*------------------------------
	 * 選択範囲のフレームをカットする
	 ------------------------------*/
	function cutFramesBySelection(beginTime) {
		var frames = copyFramesBySelection(beginTime);
		selection._reverse().each(function(i) {
			frameList[i].type = TIMELINE_FRAME_TYPE_NULL;
		} incontextof(this) );
		releaseSelection();
		invalidateNullFrame();
		return frames;
	}

	/*------------------------------
	 * フレームをカットする
	 ------------------------------*/
	function cutFrames(beginTime, endTime) {
		if (owner.selectionModeFrameEnabled) {
			if (owner.hasSelection)
				return cutFramesBySelection(...);
			else
				return cutFramesByArea(...);
		} else if (owner.selectionModeAreaEnabled) {
			if (! supportSelection
				|| ! view.isItemInArea(this))
				return [];
			if (owner.keyframePriorSideLeft)
				return cutFrameRange(...);
			else if (owner.keyframePriorSideRight)
				return cutFrameRangeRight(...);
		}
	}

	/*------------------------------
	 * 選択範囲をペーストする
	 ------------------------------*/
	function pasteSelection(pasteTime, frames) {
		if (! owner.selectionModeFrameEnabled
			&& owner.selectionModeAreaEnabled) {
			if (owner.keyframePriorSideLeft)
				pasteFrame(...);
			else if (owner.keyframePriorSideRight)
				pasteFrameRight(...);
			return;
		}

		selection = [];
		frames.each(pasteTime, owner.selectionModeFrameEnabled, function(frame, pasteTime, selectionEnabled) {
			frame = duplicateStruct(frame);
			if (frame.length === void) {
				delete frame.length;
				pasteFrame(pasteTime, [ frame ]);
				return;
			}
			frame.time += pasteTime;
			var length = frame.length;
			delete frame.length;
			var beginTime = frame.time;
			var endTime = frame.time + length;
			if (frameList.count == 0) {
				frameList.add(frame);
				frameList.add(%[ time: endTime === void ? frame.time + 1 : endTime, type: TIMELINE_FRAME_TYPE_NULL ]);
				if (selectionEnabled)
					selection.add(0);
			} else {
				var beginIndex = findFrame(beginTime, true);
				if (beginIndex < 0) {
					frameList.insert(0, frame);
					if (selectionEnabled)
						selection.add(0);
					if (frameList[1].time > endTime) 
						frameList.insert(1, %[ time: endTime, type: TIMELINE_FRAME_TYPE_NULL ]);
				} else if (frameAt(beginIndex).time != beginTime) {
					var splitFrame = duplicateStruct(frameAt(beginIndex));
					splitFrame.time = beginTime;
					frameList.insert(beginIndex + 1, splitFrame);
				}
				var endIndex = findFrame(endTime, true);
				if (frameAt(endIndex).time != endTime) {
					var splitFrame = duplicateStruct(frameAt(endIndex));
					splitFrame.time = endTime;
					frameList.insert(endIndex + 1, splitFrame);
				}
				beginIndex = findFrame(beginTime);
				endIndex = findFrame(endTime);
				for (var i = endIndex - 1; i >= beginIndex; i--) 
					frameList.erase(i);
				frameList.insert(beginIndex, frame);
				if (selectionEnabled)
					selection.add(beginIndex);
			}
		} incontextof(this) );
		invalidateNullFrame();
	}

	/**------------------------------
	 * タイムラインが右クリックされた時に呼ばれるフック関数
	 *
	 ------------------------------*/
	function onTimeLineRightClick(time) {
		owner.onTimeLineRightClick(time);
	}

	/**------------------------------
	 * タイムライン上でキーが押された時に呼ばれるフック関数
	 *
	 * @param key 仮想キーコード
	 * @param shift シフトキーの論理和
	 ------------------------------*/
	function onTimeLineKeyDown(key, shift) {
		owner.onTimeLineKeyDown(...);
	}

	/*------------------------------
	 * フレームがドラッグされた
	 ------------------------------*/
	function onFrameDragged {
	}

	// 不要なヌルフレームを削除する
	function invalidateNullFrame {
		// 連続するヌルフレームを統合する
		for (var i = 1; i < frameList.count; i++) {
			if (frameList[i - 1].type == TIMELINE_FRAME_TYPE_NULL
				&& frameList[i].type == TIMELINE_FRAME_TYPE_NULL) {
				frameList.erase(i);
				correctSelectionByRemoveIndex(i);
				i--;
				continue;
			}
		}
		// 先頭のヌルフレームを削除する
		if (frameList.count
			&& frameList[0].type == TIMELINE_FRAME_TYPE_NULL) {
			frameList.erase(0);
			correctSelectionByRemoveIndex(0);
		}
		// 連続フレームか補完フレームの場合、空リストで無ければ末尾に必ずヌルフレームを追加する
		if (frameList.count
			&& (frameList[-1].type == TIMELINE_FRAME_TYPE_CONTINUOUS
				|| frameList[-1].type == TIMELINE_FRAME_TYPE_TWEEN))
			frameList.add(%[ time: frameList[-1].time + 1, type: TIMELINE_FRAME_TYPE_NULL, content: void]);
		redrawAllFrame();
		root.owner.onRenderFrame();
		root.owner.invalidateMaxTime();
	}

	// 値の補完
	function tweenIntValue(fromValue, toValue, ratio) {
		return int(fromValue * (1 - ratio) + toValue * ratio);
	}

	function redrawFrames(frameIndices) {
		for (var i = 0; i < frameIndices.count; i++) {
			redrawFrame(frameIndices[i]);
		}
	}

	function correctSelectionByInsertIndex(insertionIndex) {
		selection.filterMap(function(index) {
			return (index < insertionIndex) ? index : index + 1;
		} incontextof (%[ insertionIndex: insertionIndex ]));
	}

	function correctSelectionByRemoveIndex(removeIndex) {
		selection.filterMap(function(index) {
			if (index < removeIndex)
				return index;
			if (index == removeIndex)
				return void;
			else
				return index - 1;
		} incontextof (%[ removeIndex: removeIndex ]));
	}

	function redrawSelectionChange(prevSelection, selection) {
		var removed = differenceSet(prevSelection, selection);
		var added = differenceSet(selection, prevSelection);
		redrawFrames(removed);
		redrawFrames(added);
	}

	function setSelectionBetweenTime(beginTime, endTime) {
		var beginIndex = findFrame(beginTime, true);
		var endIndex = findFrame(endTime, true);
		var newSelection = [];
		if (endIndex >= 0) 
			for (var i = beginIndex; i <= endIndex; i++) {
				var frame = frameAt(i);
				if (frame.type != TIMELINE_FRAME_TYPE_NULL
					&& frame.time >= beginTime
					&& frameAt(i + 1).time <= endTime + 1)
					newSelection.add(i);
			}
		setSelection(newSelection);
	}

	function selectAllFrames() {
		var indices = [];
		for (var i = 0; i < frameList.count; i++)
			if (frameList[i].type != TIMELINE_FRAME_TYPE_NULL)
				indices.add(i);
		setSelection(indices);
	}

	function setSelection(newSelection) {
		var prevSelection = selection;
		selection = newSelection;
		redrawSelectionChange(prevSelection, selection);
	}

	function addSelection(newSelection) {
		var prevSelection = selection;
		selection = unionSet(selection, newSelection);
		selection.sort();
		redrawSelectionChange(prevSelection, selection);
	}

	function removeSelection(newSelection) {
		var prevSelection = selection;
		selection = differenceSet(selection, newSelection);
		selection.sort();
		redrawSelectionChange(prevSelection, selection);
	}

	function flipSelection(newSelection) {
		var prevSelection = selection;
		var s1 = differenceSet(newSelection, selection);
		var s2 = differenceSet(selection, newSelection);
		selection = unionSet(s1, s2);
		selection.sort();
		redrawSelectionChange(prevSelection, selection);
	}

	// 選択範囲を解除する
	function releaseSelection {
		setSelection([]);
	}

	// 選択範囲を持っているか
	property hasSelection {
		getter {
			return selection.count > 0;
		}
	}

	// 選択範囲を持っているか
	property selectionCount {
		getter {
			return selection.count;
		}
	}

	// フル選択のリストを返す
	property fullSelection {
		getter {
			var result = [];
			for (var i = 0; i < frameCount; i++)
				if (frameAt(i).type != TIMELINE_FRAME_TYPE_NULL)
					result.add(i);
			return result;
		}
	}

	// 選択範囲の種類を返す
	property selectionType {
		getter {
			if (selection.count == 0)
				return TIMELINE_NO_SELECTION;
			else if (equalStruct(fullSelection, selection))
				return TIMELINE_FULL_SELECTION;
			else
				return TIMELINE_PARTIAL_SELECTION;
		}
	}

	// BGを描画する
	function drawBg(view, y, fromTime, toTime) {
		timeline_draw_bg(this, view, y, fromTime, toTime);
		return;

		// バックグラウンドを描画
		for (var time = fromTime; time < toTime; time ++) {
			var x = time * TIMELINE_FRAME_WIDTH;
			var layer;
			if (time % 60 == 0) {
				layer = view.oneSecondFrameBgLayer;
			} else if (time % 30 == 0) {
				layer = view.halfSecondFrameBgLayer;
			} else if (time % 5 == 0) {
				layer = view.fifthFrameBgLayer;
			} else {
				layer = view.normalFrameBgLayer;
			}
			view.copyRect(x, y, layer, 0, 0, TIMELINE_FRAME_WIDTH, TIMELINE_FRAME_HEIGHT);
		}
	}

	// フレームを描画する
	function drawFrame(view, layerIndex, frameIndex, y, frame, length) {
		onDrawFrame(...);
	}

	function onDrawFrame(view, layerIndex, frameIndex, y, frame, length) {
		timeline_draw_frame(this, view, layerIndex, frameIndex, y, frame, length, markerMask);
		return;

		// C++リファレンス実装
		switch (frame.type) {
		case TIMELINE_FRAME_TYPE_NULL:
			drawBg(view, y, frame.time, frame.time + length);
			return;
		case TIMELINE_FRAME_TYPE_SINGLE:
			drawBg(view, y, frame.time + 1, frame.time + length - 1);
			view.fillGradientRectLR(frame.time * TIMELINE_FRAME_WIDTH, y, TIMELINE_FRAME_WIDTH - 1, TIMELINE_FRAME_HEIGHT - 1, _singleFrameLeftColor | 0xFF000000, _singleFrameRightColor | 0xFF000000);
			return;
		case TIMELINE_FRAME_TYPE_CONTINUOUS:
		case TIMELINE_FRAME_TYPE_TWEEN:
			var leftColor, rightColor;
			if (frame.type == TIMELINE_FRAME_TYPE_CONTINUOUS) {
				leftColor = _continuousFrameLeftColor;
				rightColor = _continuousFrameRightColor;
			} else {
				leftColor = _tweenFrameLeftColor;
				rightColor = _tweenFrameRightColor;
			}
			leftColor = leftColor | 0xFF000000;
			rightColor = rightColor | 0xFF000000;
			// BG描画
			view.fillRect((frame.time + length) * TIMELINE_FRAME_WIDTH - 1, y, 1, TIMELINE_FRAME_HEIGHT, WIN_DARKEN2);
			view.fillRect(frame.time * TIMELINE_FRAME_WIDTH, y + TIMELINE_FRAME_HEIGHT - 1, length * TIMELINE_FRAME_WIDTH, 1, WIN_DARKEN2);
			view.fillGradientRectLR(frame.time * TIMELINE_FRAME_WIDTH, y,
									length * TIMELINE_FRAME_WIDTH - 1,
									TIMELINE_FRAME_HEIGHT - 1,
									leftColor, rightColor);
			var leftMarker = markerMask & TIMELINE_MARKER_MASK_LEFT;
			var rightMarker = markerMask & TIMELINE_MARKER_MASK_RIGHT;
			if (rightMarker && leftMarker && length == 1)
				rightMarker = false;
			// 左マーカー描画
			if (leftMarker)
				view.operateRect(frame.time * TIMELINE_FRAME_WIDTH, y,
								 view.frameLeftMarkerLayer, 0, 0, view.frameLeftMarkerLayer.width, view.frameLeftMarkerLayer.height);
			// 右マーカー描画
			if (rightMarker)
				view.operateRect((frame.time + length) * TIMELINE_FRAME_WIDTH - view.frameRightMarkerLayer.width, y,
								 view.frameRightMarkerLayer, 0, 0, view.frameRightMarkerLayer.width, view.frameRightMarkerLayer.height);
			// トゥイーンの破線描画
			var fromTime = frame.time + (leftMarker ? 1 : 0), toTime = frame.time + length - (rightMarker ? 1 : 0);
			if (frame.type == TIMELINE_FRAME_TYPE_TWEEN) {
				if (view.dashLineApp !== void) {
					view.drawLine(view.dashLineApp, (fromTime) * TIMELINE_FRAME_WIDTH, y + TIMELINE_FRAME_HEIGHT / 2 - 1, (toTime) * TIMELINE_FRAME_WIDTH, y + TIMELINE_FRAME_HEIGHT / 2 - 1);
				} else {
					for (var i = fromTime; i < toTime; i++) {
						view.fillRect(i * TIMELINE_FRAME_WIDTH, y + TIMELINE_FRAME_HEIGHT / 2 - 1, TIMELINE_FRAME_WIDTH / 2 - 2, 1, WIN_DARKEN2);
						view.fillRect(i * TIMELINE_FRAME_WIDTH + TIMELINE_FRAME_WIDTH / 2, y + TIMELINE_FRAME_HEIGHT / 2 - 1, TIMELINE_FRAME_WIDTH / 2 - 2, 1, WIN_DARKEN2);
					}
				}
			}
			// フレーム数描画
			if (length > 2) {
				view.canvas.fontHeight = height - 4;
				var text = string(length);
				var textWidth = view.canvas.font.getTextWidth(text);
				var l = frame.time * TIMELINE_FRAME_WIDTH + ((length * TIMELINE_FRAME_WIDTH) - textWidth) / 2;
				var t = y + int((TIMELINE_FRAME_HEIGHT - view.canvas.fontHeight) / 2) - 1;
				view.setClip(l - 1, t - 1, textWidth + 2, view.canvas.fontHeight + 2);
				view.fillGradientRectLR(frame.time * TIMELINE_FRAME_WIDTH, y,
										length * TIMELINE_FRAME_WIDTH - 1,
										TIMELINE_FRAME_HEIGHT - 1,
										leftColor, rightColor);
				view.setClip();
				view.drawText(l, t, text, WIN_DARKEN2 & 0xFFFFFF);
			}
			return;
		}
	}

	// タイムラインを描画する
	function drawTimeLine(view, layerIndex, fromTime, toTime) {
		timeline_draw_timeline(this, view, layerIndex, fromTime, toTime);
		return;

		// 以下、C++リファレンス実装。

		// 描画範囲を確定
		var y = layer.top;
		var fromFrame = findFrame(fromTime, true);
		var toFrame = findFrame(toTime, true);

		// バックグラウンドを描画
		if (fromFrame < 0 && toFrame < 0) {
			drawBg(view, y, fromTime, toTime);
		} else {
			if (fromFrame < 0)
				drawBg(view, y, fromTime, frameList[0].time);
			if (toFrame == frameList.count - 1)
				drawBg(view, y, frameList[-1].time, toTime);
		}

		// フレームを描画
		for (var i = fromFrame; i <= toFrame; i++) {
			if (i == -1)
				continue;
			var frame = frameList[i];
			var headTime, tailTime;
			headTime = frame.time;
			if (i < frameList.count - 1)
				tailTime = frameList[i + 1].time;
			else
				tailTime = headTime;
			if (! (tailTime < fromTime
				   || headTime > toTime)) {
				drawFrame(view, y, frame, tailTime - headTime);
			}
		}
		// 選択範囲描画
		if (selection !== void)
			view.colorRect(selection[0] * TIMELINE_FRAME_WIDTH, y, (selection[1] - selection[0]) * TIMELINE_FRAME_WIDTH, TIMELINE_FRAME_HEIGHT, selection[2] ? 0xFF0000 : 0, 128);
	}

	// 新規フレームを作成して返す
	function createNewFrame(time, type, content) {
		if (type == TIMELINE_FRAME_TYPE_NULL)
			content = void;
		return %[ time: time,
				  type: type,
				  content: content ];
	}

	// 連続フレームを2つに分割する
	function splitContinuousFrame(fromFrame, splitTime) {
		var result = [];
		result[0] = duplicateStruct(fromFrame);
		result[1] = createNewFrame(splitTime, fromFrame.type, duplicateStruct(fromFrame.content));
		return result;
	}

	// 補完フレームを2つに分割する
	function splitTweenFrame(fromFrame, toFrame, splitTime) {
		var result = [];
		result[0] = duplicateStruct(fromFrame);
		result[1] = createNewFrame(splitTime, fromFrame.type, tweenFrameContent(fromFrame.content, toFrame.content, (splitTime - fromFrame.time) / (toFrame.time - fromFrame.time)));
		return result;
	}

	// 補完フレームを2つに分割する(キーフレーム右側バージョン)
	function splitTweenFrameRight(fromFrame, toFrame, splitTime, frameLength) {
		var result = [];
		var beginTime = toFrame.time;
		result[0] = createNewFrame(toFrame.time, toFrame.type, tweenFrameContent(fromFrame.content, toFrame.content, (splitTime - toFrame.time) / frameLength));
		result[1] = createNewFrame(splitTime, toFrame.type, duplicateStruct(toFrame.content));
		return result;
	}

	// 指定時間の左側にあるフレームの数
	function leftSideFrameNum(time) {
		var count = 0;

		for (var i = 0; i < frameList.count; i++)
			if (frameList[i].time > time
				&& ! (i > 0
					  && frameList[i - 1].type == TIMELINE_FRAME_TYPE_NULL))
				return count - 1;
		else if (frameList[i].time >= time)
			return count;
		else if (frameList[i].type != TIMELINE_FRAME_TYPE_NULL)
			count++;

		return count;
	}

	// 指定時間の左側にあるフレームをマッピング
	function mapLeftSideFrame(time, map) {
		for (var i = 0; i < frameList.count; i++) {
			if (frameList[i].time > time)
				return;
			if (frameList[i].type != TIMELINE_FRAME_TYPE_NULL
				|| i == frameList.count - 1)
				map[frameList[i].time] = true;
		}
	}

	// フレームを移動する
	function moveFrame(fromTime, toTime, saveLength = false, render = true) {
		if (fromTime == toTime)
			;
		// 左へ移動(配列による指定)
		if (typeof(fromTime) == "Object") {
			// 時間指定が配列で来た場合の対応
			var leftIndex = 0;
			for (var i = 0; i < frameList.count; i++) {
				var frame = frameList[i];
				// 変化した時間以前なら、いじらない。
				if (frame.time < fromTime[leftIndex]) {
					;
				}
				// 変化した時間以降なら、直接シフトして終わり
				else if (frame.time >= fromTime[-1]) {
					frame.time += - fromTime[-1] + toTime[-1];
				}
				// 時間指定配列のindexを、現在フレームの時間が範囲内に入るまで進める
				else {
					while (frame.time >= fromTime[leftIndex + 1])
						leftIndex++;
					// 時間を更新
					frame.time += -fromTime[leftIndex] + toTime[leftIndex];
				}
				// 直前のフレームがアレだったら削除
				if (i > 0
					&& frameList[i - 1].time >= frameList[i].time) {
					frameList.erase(i - 1);
					i--;
				}
			}
		}
		// 左へ移動
		else if (toTime < fromTime) {
			var curFrame = frameAt(findFrame(fromTime, true));

			for (var i = frameList.count - 1; i >= 0; i--) {
				var frame = frameList[i];

				if (frame.time > fromTime) {
					if (saveLength)
						frame.time += toTime - fromTime;
				} else if (frame.time == fromTime)
					frame.time = toTime;
				else {
					var baseTime = toTime + 1;
					if (i < frameList.count - 1)
						baseTime = Math.min(frameList[i + 1].time, baseTime);
					if (frame.time >= baseTime) {
						if (frame.type == TIMELINE_FRAME_TYPE_NULL
							&& i < frameList.count - 1
							&& frameList[i + 1].time == baseTime) {
							frameList.erase(i);
						} else {
							frame.time = baseTime - 1;
						}
					}
				}
			}
			// 右へ移動
		} else {
			for (var i = 0; i < frameList.count; i++) {
				var frame = frameList[i];

				if (frame.time < fromTime)
					;
				else if (saveLength)
					frame.time += toTime - fromTime;
				else if (frame.time == fromTime)
					frame.time = toTime;
				else if (i > 0
						 && frame.time <= frameList[i - 1].time) {
					if (frameList[i - 1].type == TIMELINE_FRAME_TYPE_NULL) {
						frame.time = frameList[i - 1].time;
						frameList.erase(i - 1);
						i--;
					} else {
						frame.time = frameList[i - 1].time + 1;
					}
				}
			}
		}
		if (render) {
			if (this instanceof "KTimeLineLoopItem")
				root.redrawAllItemsView();
			else
				redrawAllFrame();
		}
	}

	//----------------------------------------------------------------------
	// ポイントフック
	function onPointEnter(frameIndex) {
	}

	function onPointLeave(frameIndex) {
	}

	//----------------------------------------------------------------------
	// マウスイベント管理
	var _customMouseEvents = [];

	function clearCustomMouseEvents() {
		_customMouseEvents.clear();
	}

	function registerCustomMouseEvent(frameIndex, range, cursor, callbacks) {
		_customMouseEvents.add(%[ frameIndex: frameIndex,
								  range: range,
								  cursor: cursor,
								  callbacks: callbacks ]);
	}

	function getCustomMouseEvent(x, y) {
		var events = _customMouseEvents._select(x, y, function(event, x, y) {
			return event.range.contains(x, y);
		});
		if (events.count)
			return events[0];
		else
			return void;
	}

	function getFrameRange(frameIndex) {
		var frame = frameList[frameIndex];
		var nextFrame = frameList[frameIndex + 1];
		var length = nextFrame.time - frame.time;
		return new KRect(TIMELINE_FRAME_WIDTH * frame.time, top, TIMELINE_FRAME_WIDTH * length, height);
	}
};



/**----------------------------------------------------------------------
 * タイムラインループ設定アイテム
 ----------------------------------------------------------------------*/
class KTimeLineLoopItem extends KTimeLineItem
{
	/**------------------------------
	 * コンストラクタ
	 *
	 * @param label ラベル
	 * @param name 名前
	 *
	 * タイムラインループアイテムを取得します。
	 *
	 * このアイテムをタイムラインに追加することで、KTimeLineControl の
	 * loopBeginTime, loopEndTime の2種類のプロパティを、GUIで設定できる
	 * ようになります
	 ------------------------------*/
	function KTimeLineLoopItem() {
		super.KTimeLineItem(...);
		markerMask = TIMELINE_MARKER_MASK_LEFT | TIMELINE_MARKER_MASK_RIGHT;
		supportSelection = false;
	}

	property singleFrameLeftColor {
		getter {
			return view.widgetStyle.loopSingleFrameColor;
		}
	}

	property singleFrameRightColor {
		getter {
			return view.widgetStyle.loopSingleFrameColor;
		}
	}

	property continuousFrameLeftColor {
		getter {
			return view.widgetStyle.loopContinuousFrameColor;
		}
	}

	property continuousFrameRightColor {
		getter {
			return view.widgetStyle.loopContinuousFrameColor;
		}
	}

	var contextmenu_loopBegin = "ループの始点を設定する";
	var contextmenu_loopEnd = "ループの終点を設定する";
	var contextmenu_lastFrame = "最終フレームを設定する";
	var contextmenu_release = "ループ/最終フレームを解除する";

	function onBuildTimeLineContextMenu(menu, time) {
		menu.addItem(contextmenu_loopBegin, "", true, funccall(this.onSetLoopBeginTime, time));
		menu.addItem(contextmenu_loopEnd, "", true, funccall(this.onSetLoopEndTime, time + 1));
		menu.addSeparator();
		menu.addItem(contextmenu_lastFrame, "", true, funccall(this.onSetLastTime, time));
		menu.addSeparator();
		menu.addItem(contextmenu_release, "", hasLastFrame || hasLoopFrame, funccall(this.onRelease));
	}

	function onTimeLineRightClick(time) {
		var menu = new KContextMenu(window);
		onBuildTimeLineContextMenu(menu, time);
		owner.onBuildCommonTimeLineContextMenu(menu);
		menu.show();
	}

	property hasLoopFrame {
		getter {
			return frameCount != 0
				&& frameAt(0).type == TIMELINE_FRAME_TYPE_CONTINUOUS;
		}
	}

	property hasLastFrame {
		getter {
			return frameCount != 0
				&& frameAt(0).type == TIMELINE_FRAME_TYPE_SINGLE;
		}
	}

	property primaryLastTime {
		getter {
			if (! hasLastFrame)
				return -1;
			else
				return frameAt(0).time;
		}
		setter(v) {
			if (v == -1) {
				if (hasLastFrame) {
					frameList = [];
					root.redrawAllItemsView();
				}
				return;
			}
			setLoopTime(-1, -1);
			if (frameCount == 0) {
				frameList[0] = createNewFrame(v, TIMELINE_FRAME_TYPE_SINGLE);
			} else {
				frameList[0].time = v;
			}
			root.redrawAllItemsView();
		}
	}

	property loopBeginTime {
		getter {
			if (! hasLoopFrame)
				return -1;
			else
				return frameAt(0).time;
		}
		setter(v) {
			if (v == -1) {
				if (hasLoopFrame) {
					frameList = [];
					root.redrawAllItemsView();
				}
				return;
			}
			primaryLastTime = -1;
			if (frameCount == 0) {
				frameList[0] = createNewFrame(v, TIMELINE_FRAME_TYPE_CONTINUOUS);
				frameList[1] = createNewFrame(v + 1, TIMELINE_FRAME_TYPE_NULL);
			} else {
				frameAt(0).time = v;
				if (frameAt(0).time >= frameAt(1).time)
					frameAt(1).time = v + 1;
			}
			root.redrawAllItemsView();
		}
	}

	property loopEndTime {
		getter {
			if (! hasLoopFrame)
				return -1;
			else
				return frameAt(1).time;
		}
		setter(v) {
			if (v == -1) {
				if (hasLoopFrame) {
					frameList = [];
					root.redrawAllItemsView();
				}
				return;
			}
			primaryLastTime = -1;
			if (v == 0)
				v = 1;
			if (frameCount == 0) {
				frameList[0] = createNewFrame(0, TIMELINE_FRAME_TYPE_CONTINUOUS);
				frameList[1] = createNewFrame(v, TIMELINE_FRAME_TYPE_NULL);
			} else {
				frameAt(1).time = v;
				if (frameAt(0).time >= frameAt(1).time)
					frameAt(0).time = v - 1;
			}
			root.redrawAllItemsView();
		}
	}

	function setLoopTime(beginTime, endTime) {
		if (beginTime == -1) {
			if (hasLoopFrame)
				frameList = [];
		} else {
			primaryLastTime = -1;
			if (frameCount == 0) {
				frameList[0] = createNewFrame(beginTime, TIMELINE_FRAME_TYPE_CONTINUOUS);
				frameList[1] = createNewFrame(endTime, TIMELINE_FRAME_TYPE_NULL);
			} else {
				frameAt(0).time = beginTime;
				frameAt(1).time = endTime;
			}
		}
		root.redrawAllItemsView();
	}

	function onSetLoopBeginTime(time) {
		loopBeginTime = time;
		onLoopModifiedByMenu();
	}

	function onSetLoopEndTime(time) {
		loopEndTime = time;
		onLoopModifiedByMenu();
	}

	function onRelease {
		loopBeginTime = -1;
		primaryLastTime = -1;
		onLoopModifiedByMenu();
	}

	function onSetLastTime(time) {
		primaryLastTime = time;
		onLoopModifiedByMenu();
	}

	function onLoopModifiedByMenu {
	}
}

