//
// $Id$
//


/*----------------------------------------------------------------------
 * 定数(内部定数)
 ----------------------------------------------------------------------*/
global.TIMELINE_FRAME_HEIGHT = 14;
global.TIMELINE_LOCATOR_HEIGHT = 20;

global.TIMELINE_FRAME_TYPE_NULL = 0;
global.TIMELINE_FRAME_TYPE_SINGLE = 1;
global.TIMELINE_FRAME_TYPE_CONTINUOUS = 2;
global.TIMELINE_FRAME_TYPE_TWEEN = 3;

global.TIMELINE_MARKER_MASK_NONE = 0;
global.TIMELINE_MARKER_MASK_LEFT = 1;
global.TIMELINE_MARKER_MASK_RIGHT = 2;

global.TIMELINE_FRAME_WIDTH_LIST = [ 4, 6, 10, 14 ];
global.TIMELINE_FRAME_WIDTH_LABEL_LIST = [ "SS", "S", "M", "L" ];

global.TIMELINE_NO_SELECTION = 0;
global.TIMELINE_PARTIAL_SELECTION = 1;
global.TIMELINE_FULL_SELECTION = 2;

global.TIMELINE_SELECTION_MODE_MASK_RANGE = 1;
global.TIMELINE_SELECTION_MODE_MASK_FRAME = 2;
global.TIMELINE_KEYFRAME_PRIOR_SIDE_LEFT = 0;
global.TIMELINE_KEYFRAME_PRIOR_SIDE_RIGHT = 1;


/*----------------------------------------------------------------------
 * タイムラインユーティリティ
 ----------------------------------------------------------------------*/
function ktimeline_shallow_copy_frame_list(frameList)
{
	var newFrameList = [];
	for (var i = 0; i < frameList.count; i++) {
		var newFrame = %[];
		(Dictionary.assign incontextof newFrame)(frameList[i]);
		newFrameList.add(newFrame);
	}
	return newFrameList;
}

function ktimeline_invalidate_null_frame(frameList)
{
	timeline_invalidate_null_frame(frameList);
	return;

	// 連続するヌルフレームを統合する
	for (var i = 1; i < frameList.count; i++) {
		if (frameList[i - 1].type == TIMELINE_FRAME_TYPE_NULL
			&& frameList[i].type == TIMELINE_FRAME_TYPE_NULL) {
			frameList.erase(i);
			i--;
			continue;
		}
	}
	// 先頭のヌルフレームを削除する
	if (frameList.count
		&& frameList[0].type == TIMELINE_FRAME_TYPE_NULL)
		frameList.erase(0);
	// 連続フレームか補完フレームの場合、空リストで無ければ末尾に必ずヌルフレームを追加する
	if (frameList.count
		&& (frameList[-1].type == TIMELINE_FRAME_TYPE_CONTINUOUS
			|| frameList[-1].type == TIMELINE_FRAME_TYPE_TWEEN))
		frameList.add(%[ time: frameList[-1].time + 1, type: TIMELINE_FRAME_TYPE_NULL, content: void]);

	// フレームの重複や入れ替わりがあったら警告
	for (var i = 0; i < frameList.count - 1; i++) {
		var frame = frameList[i];
		var nextFrame = frameList[i + 1];
		if (frame.time >= nextFrame.time)
			Debug.message(format("*** WARNING ***: timeline frame overlap on frame{0}({1}) and frame{2}({3})",
								 i, frame.time, i + 1, nextFrame.time));
	}
}


function ktimeline_fix_invalid_frame(frameList)
{
	for (var i = frameList.count - 1; i > 0; i--) {
		if (frameList[i - 1].time >= frameList[i].time)
			frameList.erase(i - 1);
	}
	ktimeline_invalidate_null_frame(frameList);
}

Scripts.execStorage("KTimeLineLocator.tjs");
Scripts.execStorage("KTimeLineLayerView.tjs");
Scripts.execStorage("KTimeLineLayerList.tjs");
Scripts.execStorage("KTimeLineItem.tjs");


/**----------------------------------------------------------------------
 * フレーム指定用TextInput
 ----------------------------------------------------------------------*/
class KFrameTextInput extends KTextInput
{
	var owner;
	function KFrameTextInput(_owner, window, options) {
		owner = _owner;
		super.KTextInput(window, options);
	}

	function onValueModified(value) {
		super.onValueModified(value);
		owner.selectedTime = value;
		owner._layerView.notifyMove();
	}
}

/**----------------------------------------------------------------------
 * タイムラインコントロール
 ----------------------------------------------------------------------*/
global.KTimelineControlWidgetStyleDefinition =
	[
			%[ key: "layerListId", defaultValue: "" ],
			%[ key: "layerViewId", defaultValue: "" ],
			%[ key: "timeLocatorId", defaultValue: "" ],
			%[ key: "titleLabelId", defaultValue: "" ],
			%[ key: "statusBarId", defaultValue: "" ],
			%[ key: "frameTextId", defaultValue: "" ]
	];


class KTimeLineControl extends KEntity
{
	// 辞書
	var dict;
	// ラベル
	var _label;
	// 現在選択している時間
	var _selectedTime;
	//
	var _timeInputEnabled = null;
	// fps
	var _framePerSecond;
	// 再生中か？
	var _playing;
	// 再生用のタイマー
	var _playTimer;
	// プレイ開始システム時刻
	var _playBeginTick;
	// プレイ開始時間
	var _playBeginTime;
	// ビュー表示サイズ
	var _viewWidth = 2;
	var _frameWidth;
	var frameWidthDispatcher;
	// 時間選択時の再レンダリング
	var renderAtTimeModification = true;
	// 検索対象
	var searchTarget;
	// ループ開始時間
	var _loopBeginTime = -1;
	// ループ終了時間
	var _loopEndTime = -1;
	// 再生終了時間
	var _lastTime = -1;
	// 編集可能？
	var _editable = true;

	var baseWidget;

	var extendListSelectionFromView = false;
	var copySingleFrameAsNoWidth = false;
	var selectionModeMask = TIMELINE_SELECTION_MODE_MASK_RANGE | TIMELINE_SELECTION_MODE_MASK_FRAME;
	var keyframePriorSide = TIMELINE_KEYFRAME_PRIOR_SIDE_LEFT;

	/**------------------------------
	 * コンストラクタ
	 *
	 * @param window ウィンドウ
	 * @param name 名前
	 *
	 * タイムラインコントロールを作成する。
	 *
	 * 以下の関数群を使い、KTimeLineItem 派生クラスのオブジェクトを登録できる。
	 * KTimeLineItemはKListItemの派生クラスであり、通常のリストアイテム同様に入れ子の
	 * リストを形成できる。
	 *
	 * - childCount 子アイテムをカウントする
	 * - childAt(index) 子アイテムを参照する
	 * - add(item) 子アイテムを追加する
	 * - insert(index, item) 子アイテムを挿入する
	 * - remove(item) 子アイテムを削除する
	 * - removeAll(doInvalidate) 子アイテムを全て削除する
	 *
	 * コントロールの挙動を制御するために、以下の関数群が使用できる。
	 *
	 * - label ラベル
	 * - resize リサイズハンドルを表示するかどうか
	 *
	 * タイムラインのパラメータは以下の関数で取得、設定できる。
	 *
	 * - selectedTime 現在ポイントされている時間
	 * - selectedLayer 現在ポイントされているレイヤ
	 * - loopBeginTime ループの開始時間を設定、取得する
	 * - loopEndTime ループの終了時間を設定、取得する
	 * - setLoopTime(beginTime, endTime) ループの始点と終点を同時に設定する
	 *
	 * タイムラインコントロールはタイムラインの再生機能を持っている。
	 * 以下の関数群でその制御を行う。
	 *
	 * - framePerSecond fpsを設定する
	 * - playing 再生中かどうか。
	 * - play() 再生を開始する
	 * - stop() 再生を停止する
	 *
	 * 特定のタイミングで以下のイベント関数が呼ばれる
	 *
	 * - onTimeLocatorRightClick(time) タイムロケーターが右クリックされた時に呼ばれる
	 * - onTimeLineRightClick() タイムラインが右クリックされた時に呼ばれる
	 * - onTimeLineKeyDown(key, shift) タイムラインでキーが押された時に呼ばれる
	 * - onMultipleFrameDragged() 複数フレームがまとめてドラッグされた
	 * - onRenderFrame() フレームのレンダリングが必要な時に呼ばれる
	 * - onTimeSelect(time) ポイントされている時間が変更された時に呼ばれる
	 * - onLayerSelect(layer) ポイントされているレイヤが変更された時に呼ばれる
	 * - onPlay() 再生開始時に呼ばれる
	 * - onStop(playOverLastFrame) 再生停止時に呼ばれる
	 ------------------------------*/
	function KTimeLineControl(window, options) {
		super.KEntity(...);

		// ウィジェット生成
		_selectedTime = 0;
		extendListSelectionFromView = getOption("extendListSelectionFromView", false);
		copySingleFrameAsNoWidth = getOption("copySingleFrameAsNoWidth", false);

		baseWidget = new KHorizontalSpliterLayout(window, %[ name: name + "_spliter", splitRatio: 0,
															 style: %[ margin: 0,
																	   isClass: %[ KWidget: %[ margin: 0, alignHorizontal: ALIGN_LEFT, alignVertical: ALIGN_CENTER ]
																				 ]] ]);
		baseWidget.parent = this;
		baseWidget.add(new global.KGridLayout(window, "_leftGrid"));
		baseWidget.add(new global.KGridLayout(window, "_rightGrid"));
		_leftGrid.isAvoidDictionaryRegistration = true;
		_rightGrid.isAvoidDictionaryRegistration = true;
		_leftGrid.add(0, 1, new KScrollLayout(window, true, true, "_layerListScroll"));
		_layerListScroll.hideHorizontalBar = true;
		_layerListScroll.hideVerticalBar = true;
		_layerListScroll.add(new timelineLayerListClass(window, this, "_layerList"));
		_rightGrid.add(0, 0, new KScrollLayout(window, %[ horizontal: true, vertical: false,
														  name: "_timeLocatorScroll",
														  hideHorizontalBar: true,
														  marginalMinHeight: 0,
														  marginalMaxHeight: 0 ,
														  style: %[ borderStyle: BORDER_STYLE_NONE,
																	borderWidthTop: 0,
																	borderWidthBottom: 0,
																  ] ]));
		//    _timeLocatorScroll.hideHorizontalBar = true;
		_timeLocatorScroll.add(new KTimeLineTimeLocator(window, this, "_timeLocator"));
		_rightGrid.add(0, 1, new KScrollLayout(window, true, true, "_layerViewScroll"), 2);
		_layerViewScroll.add(new timelineLayerViewClass(window, this, "_layerView"));
		_leftGrid.add(0, 0, new KGridLayout(window, %[ name: "_titleGrid" ]));
		_titleGrid.add(0, 0, new KTextLabel(window, %[ name: "_titleLabel" ]));
		_titleGrid.add(1, 0, new KGridLayout(window, "additionalControlGrid"));
		_titleGrid.add(2, 0, new KTextButton(window, %[ label: "M", name: "_viewWidthButton", style: %[ alignHorizontal: ALIGN_RIGHT, alignVertical: ALIGN_CENTER, padding: 2, fontHeight: 12 ] ]));
		_titleGrid.add(3, 0, new KGridLayout(window, "additionalControlGrid2"));
		_leftGrid.add(0, 2, new global.KGridLayout(window, "_frameGrid"));
		_frameGrid.add(0, 0, new KFrameTextInput(this, window, %[ type: TEXT_DIGIT, name: "_frameText" ]));
		_frameGrid.add(1, 0, new KTextLabel(window, %[ name: "_statusBar" ]));
		_frameText.visible = false;

		_rightGrid.add(1, 0, new KSpacer(window, %[ width: _layerViewScroll.verticalBar.width, height: 0, name: "_rightTopSpacer" ]));
		_layerViewScroll.onChildViewModified = this.onLayerViewModified;
		_layerListScroll.onChildViewModified = this.onLayerListModified;
		_layerList.timeLineView = _layerView;
		_layerList.onRelocate = onListRelocate;
		_viewWidthButton.focusable = false;
		_viewWidthButton.onValueModified = this.onViewWidthChange;

		// パラメータ初期設定
		_framePerSecond = 10;
		_playTimer = new Timer(this.onPlayTimer, "");
		_playTimer.capacity = 1;
		_playTimer.interval = 1000 / _framePerSecond;

		// ステータスバー生成
		timeInputEnabled = 0;
		redrawStatusBar();

		frameWidthDispatcher = new KInterpolateDispatcher(this, %[ valueName: "frameWidth",
																   dispatchName: "",
																   exponent: 1 ]);

		_frameWidth = TIMELINE_FRAME_WIDTH_LIST[_viewWidth];
		multipleSelection = getOption("multipleSelection", false);
		selectionModeMask = getOption("selectionModeMask", selectionModeMask);
		keyframePriorSide = getOption("keyframePriorSide", keyframePriorSide);
	}

	/*------------------------------
	 * ファイナライザ
	 ------------------------------*/
	function finalize {
		invalidate frameWidthDispatcher;
		discard(_playTimer);
		super.finalize(...);
	}

	property widgetStyleDefinition {
		getter {
			return concatArray(super.widgetStyleDefinition, KTimelineControlWidgetStyleDefinition);
		}
	}

	function onChildMinMaxSizeModified() {
		redrawContents();
	}

	function onDrawContents() {
		_layerList.id = widgetStyle.layerListId;
		_layerView.id = widgetStyle.layerViewId;
		_timeLocator.id = widgetStyle.timeLocatorId;
		_titleLabel.id = widgetStyle.titleLabelId;
		_statusBar.id = widgetStyle.statusBarId;
		_frameText.id = widgetStyle.frameTextId;
		_rightTopSpacer.setFixedSize(_layerViewScroll.verticalBar.width, 0);
		setMinMaxSize(baseWidget.minWidth + borderPaddingWidth,
					  baseWidget.minHeight + borderPaddingHeight,
					  baseWidget.maxWidth + borderPaddingWidth,
					  baseWidget.maxHeight + borderPaddingHeight);
		drawBorder(borderStyle, 0, 0, width, height);
		embedChild(0, 0, width, height, baseWidget);
	}

	/*------------------------------
	 * 辞書登録
	 ------------------------------*/
	function onUnserialize(dict, key) {
		viewWidth = dict.init(key + "_view_width", viewWidth);
	}

	function onSerialize(dict, key) {
			dict.set(key + "_view_width", viewWidth);
	}

	/*------------------------------
	 * レイヤーリストクラス
	 ------------------------------*/
	property timelineLayerListClass {
		getter {
			return KTimeLineLayerList;
		}
	}

	/*------------------------------
	 * レイヤービュークラス
	 ------------------------------*/
	property timelineLayerViewClass {
		getter {
			return KTimeLineLayerView;
		}
	}

	/**------------------------------
	 * 子アイテムをカウントする
	 *
	 * @return 子アイテム数
	 ------------------------------*/
	property childCount {
		getter {
			return _layerList.childCount;
		}
	}

	/**------------------------------
	 * 子アイテムを参照する
	 *
	 * @param index インデックス
	 * @return 子アイテム
	 ------------------------------*/
	function childAt(index) {
		return _layerList.childAt(index);
	}

	/**------------------------------
	 * 子アイテムを追加する
	 *
	 * @param item アイテム
	 ------------------------------*/
	function add(item) {
		_layerList.add(item);
	}

	/**------------------------------
	 * 子アイテムを挿入する
	 *
	 * @param index インデックス
	 * @param item アイテム
	 ------------------------------*/
	function insert(index, item) {
		_layerList.insert(index, item);
	}

	/**------------------------------
	 * 子アイテムを削除する
	 *
	 * @param item アイテム
	 * @param doInvalidate invalidateするかどうか
	 * @return 削除したアイテム自身
	 ------------------------------*/
	function remove(item, doInvalidate = true) {
		_layerList.remove(item, doInvalidate);
	}

	/**------------------------------
	 * 子アイテムを全て削除する
	 *
	 * @param doInvalidate 取り除いた子ウィジェットを無効化するか
	 ------------------------------*/
	function removeAll(doInvalidate = true) {
		_layerList.removeAll(doInvalidate);
	}

	/**------------------------------
	 * ラベル
	 *
	 * @param v ラベル
	 * @return ラベル
	 *
	 * コントロール左上に表示されるラベルの内容を設定する
	 ------------------------------*/
	property label {
		getter {
			return _titleLabel.label;
		}
		setter(v) {
			_titleLabel.label = v;
		}
	}

	/**------------------------------
	 * リサイズハンドルを表示するかどうか
	 *
	 * @param v 表示/非表示
	 * @return 表示/非表示
	 ------------------------------*/
	property resize {
		getter {
			return _layerViewScroll.resize;
		}
		setter(v) {
			_layerViewScroll.resize = v;
		}
	}

	/**------------------------------
	 * 現在ポイントされている時間
	 *
	 * @param v 時間
	 * @return 時間
	 ------------------------------*/
	property selectedTime {
		getter {
			return _selectedTime;
		}
		setter(v) {
			v = int(Math.max(0, v));
			if (_selectedTime == v)
				return;
			var prevSelectedFrame = _selectedTime;
			_selectedTime = v;
			//      if (! playing) {
			var w = 50;
			_timeLocator.redrawRect(prevSelectedFrame * TIMELINE_FRAME_WIDTH - w /  2, 0, w, _timeLocator.height);
			_timeLocator.redrawRect(_selectedTime * TIMELINE_FRAME_WIDTH - w / 2, 0, w, _timeLocator.height);
			updateCursor();
			//      }
			onTimeSelect(v);
			if (renderAtTimeModification)
				onRenderFrame();
			redrawStatusBar();
			invalidateMaxTime(false);
		}
	}

	/**------------------------------
	 * 0以外を設定すると選択フレーム位置をテキスト入力できる
	 ------------------------------*/
	property timeInputEnabled {
		getter {
			return _timeInputEnabled;
		}
		setter(v) {
			if(_timeInputEnabled != v){
				_timeInputEnabled = v;
				_frameText.visible = v;
				redrawStatusBar();
			}
		}
	}

	/**------------------------------
	 * 現在ポイントされているレイヤ
	 *
	 * @param v レイヤインデックス
	 * @return レイヤインデックス
	 *
	 * 現在ポイントされているレイヤのインデックスを設定・取得する
	 *
	 * インデックスはその時点で「表示されている」レイヤに対応する物であり、
	 * 表示を閉じているレイヤがある場合は必ずしもレイヤツリーの構造とは一致しない事に注意。
	 *
	 * 現在ポイントされているレイヤが存在しない場合-1を返す。
	 ------------------------------*/
	property selectedLayer {
		getter {
			return _layerList.selectionIndex;
		}
		setter(v) {
			if (v >= _layerList.drawItemList.count)
				v = _layerList.drawItemList.count - 1;
			if (v < 0)
				return;
			if (drawItemList.find(_layerList.focusedItem) == v)
				return;
			updateCursor();
			_layerList.focusOnSelect = false;
			_layerList.drawItemList[v].select();
			_layerList.focusOnSelect = true;
			onLayerSelect(v);
			onRenderFrame();
		}
	}

	/**------------------------------
	 * fps(frame per second)
	 *
	 * @param v fps
	 * @return fps
	 *
	 * 何フレームが1秒に相当するかを設定する。
	 *------------------------------*/
	property framePerSecond {
		getter {
			return _framePerSecond;
		}
		setter(v) {
			_framePerSecond = v;
			_playTimer.interval = 1000 / v;
			_layerView.redrawAll();
			redrawStatusBar();
		}
	}

	/**------------------------------
	 * 選択をしているかどうか
	 *
	 * @return 選択をしているかどうか
	 ------------------------------*/
	property hasListSelection {
		getter {
			return list.hasSelection;
		}
	}

	property hasSingleListSelection {
		getter {
			return list.hasSingleSelection;
		}
	}

	property hasMultipleListSelection {
		getter {
			return list.hasMultipleSelection;
		}
	}

	property hasSelection {
		getter {
			return _layerView.hasSelection;
		}
	}

	property hasSingleSelection {
		getter {
			return view.hasSingleSelection;
		}
	}

	property hasMultipleSelection {
		getter {
			return view.hasMultipleSelection;
		}
	}

	function selectCurrentPoint() {
		view.selectCurrentPoint();
	}

	//----------------------------------------------------------------------
	// エリア指定をしているかどうか
	property hasArea {
		getter {
			return _layerView.hasArea;
		}
	}

	property hasWorkZone {
		getter {
			return _layerView.hasWorkZone;
		}
	}

	//----------------------------------------------------------------------
	// viewの参照
	property view {
		getter {
			return _layerView;
		}
	}

	///----------------------------------------------------------------------
	// listの参照
	property list {
		getter {
			return _layerList;
		}
	}

	/*------------------------------
	 * 表示中のリストアイテムの一覧
	 *
	 * @return アイテムの一覧
	 ------------------------------*/
	property drawItemList {
		getter {
			var result = [];
			result.assign(_layerList.drawItemList);
			return result;
		}
	}

	/*------------------------------
	 * 範囲選択の対象となる表示アイテムの一覧
	 *
	 * @return アイテムの一覧
	 ------------------------------*/
	property selectionTargetDrawItemList {
		getter {
			return _layerList.drawItemList._select(function(item) {
				return item.supportSelection;
			});
		}
	}

	property pointEffectiveFrame {
		getter {
			return selectedLayer >= 0
				&& drawItemList[selectedLayer].supportSelection
				&& drawItemList[selectedLayer].pointEffectiveFrame;
		}
	}

	property pointFrameHead {
		getter {
			return selectedLayer >= 0
				&& drawItemList[selectedLayer].supportSelection
				&& drawItemList[selectedLayer].pointFrameHead;
		}
	}

	property pointEffectiveFrameHead {
		getter {
			return selectedLayer >= 0
				&& drawItemList[selectedLayer].supportSelection
				&& drawItemList[selectedLayer].pointEffectiveFrameHead;
		}
	}

	/**------------------------------
	 * 再生中かどうか
	 *
	 * @param v 再生中かどうか
	 * @return 再生中かどうか
	 ------------------------------*/
	property playing {
		getter {
			return _playing;
		}
		setter(v) {
			if (_playing == v)
				return;
			if (v)
				play();
			else
				stop();
		}
	}

	/**------------------------------
	 * 再生開始
	 *
	 * タイムラインの再生を開始する
	 ------------------------------*/
	function play {
		if (_playing)
			return;
		_playing = true;
		_playBeginTick = System.getTickCount();
		_playBeginTime = selectedTime;
		_playTimer.enabled = true;
		onPlay();
	}

	/**------------------------------
	 * 再生停止
	 *
	 * タイムラインの再生を停止する
	 ------------------------------*/
	function stop {
		if (! _playing)
			return;
		doStop();
	}

	/**------------------------------
	 * セレクションが更新された
	 *
	 * @param time クリックされた時間
	 ------------------------------*/
	function onSelectionModified {
	}

	/**------------------------------
	 * タイムロケーターが右クリックされた
	 *
	 * @param time クリックされた時間
	 ------------------------------*/
	function onTimeLocatorRightClick(time) {
	}

	/**------------------------------
	 * タイムラインが右クリックされた
	 ------------------------------*/
	function onTimeLineRightClick {
	}

	/**------------------------------
	 * タイムラインが右クリックされた
	 ------------------------------*/
	function onTimeLineRightClick {
		var menu = new KContextMenu(window);
		onBuildCommonTimeLineContextMenu(menu);
		if (menu.childCount == 0)
			invalidate menu;
		else
			menu.show();
	}

	/**------------------------------
	 * 共通コンテキストメニューを作る
	 ------------------------------*/
	function onBuildCommonTimeLineContextMenu() {
	}

	/*------------------------------
	 * 複数のフレームがまとめてドラッグされた
	 ------------------------------*/
	function onMultipleFrameDragged {
	}

	/**------------------------------
	 * タイムラインが選択状態でキーが押された
	 *
	 * @param key 仮想キーコード
	 * @param shift シフトキーの論理和
	 ------------------------------*/
	function onTimeLineKeyDown(key, shift) {
	}

	/**------------------------------
	 * フレームのレンダリングが必要
	 *
	 * フレームのレンダリングが必要だと判断されたタイミングで呼ばれる。
	 * 具体的には以下のシチュエーションが該当する
	 *
	 * - アイテムに新規フレームを追加した時
	 * - アイテムからフレームを削除した時
	 * - アイテムにキーフレームを挿入した時
	 * - アイテムからキーフレームを削除した時
	 * - アイテムをアンシリライズした時
	 * - アイテムをドラッグして移動した時
	 * - ポイントしている時間が変更された時
	 * - ポイントされているレイヤが変更された時
	 ------------------------------*/
	function onRenderFrame {
	}

	/**------------------------------
	 * ポイントされている時間が変更された時に呼ばれる
	 *
	 * @param time 時間
	 ------------------------------*/
	function onTimeSelect(time) {
	}

	/**------------------------------
	 * ポイントされているレイヤが変更された時に呼ばれる
	 *
	 * @param layer レイヤインデックス
	 ------------------------------*/
	function onLayerSelect(layer) {
	}

	/**------------------------------
	 * 再生開始時に呼ばれる
	 ------------------------------*/
	function onPlay {
	}

	/**------------------------------
	 * 再生停止時に呼ばれる
	 *
	 * @param playOverLastFrame 最終フレームまで再生したか？
	 *
	 * 再生停止時に呼ばれるイベント関数。
	 * 最終フレームまで再生が終了して自動的に停止した場合、
	 * playOverLastFrameがtrueになって呼ばれる。
	 ------------------------------*/
	function onStop(playOverLastFrame) {
	}

	/**------------------------------
	 * ビューのドラッグが発生した時のコールバック
	 ------------------------------*/
	function onViewDragEnter() {
	}

	function onViewDragMove() {
	}

	function onViewDragLeave() {
	}

	// 実際の停止処理
	function doStop(playOverLastFrame = false) {
		_playing = false;
		_playTimer.enabled = false;
		onStop(playOverLastFrame);
		_timeLocator.redrawAll();
		_layerView.redrawAll();
		updateCursor();
	}

	// 再生タイマの呼び先
	function onPlayTimer {
		var tick = System.getTickCount();
		var time = _playBeginTime + Math.round((tick - _playBeginTick) / _playTimer.interval);
		var loopBegin = loopBeginTime, loopEnd = loopEndTime;
		if (loopBegin >= 0) {
			if (time < loopBegin)
				selectedTime = time;
			else
				selectedTime = loopBegin + (time - loopBegin) % (loopEnd - loopBegin);
		} else {
			if (time <= lastTime) {
				selectedTime = time;
			} else {
				selectedTime = lastTime;
				doStop(true);
			}
		}
	}

	// ステータスバーを再描画
	function redrawStatusBar {
		if(timeInputEnabled){
			_frameText.value = string(selectedTime);
			_statusBar.label = " %0.1ffps  %0.1fs".sprintf(framePerSecond, selectedTime / framePerSecond);
		} else {
			_statusBar.label = "  %d  %0.1ffps  %0.1fs".sprintf(selectedTime, framePerSecond, selectedTime / framePerSecond);
		}
	}

	// タイムラインビューの横幅を必要に応じて自動的に拡張する
	function invalidateMaxTime(calcLastTime = true) {
		var size = _layerView.maxWidth;
		size = Math.max(size, (int(selectedTime / 100) * 100 + 200) * TIMELINE_FRAME_WIDTH);
		if (calcLastTime)
			size = Math.max(size, (int(lastTime  / 100) * 100 + 200) * TIMELINE_FRAME_WIDTH);
		size = int(size);
		if (size <= _layerView.maxWidth)
			return;
		invalidateMaxWidth(size);
	}

	function invalidateMaxWidth(size) {
		size = Math.max(size, width);
		_layerView.setMinMaxSize(size, _layerView.minHeight, size, _layerView.maxHeight);
		_timeLocator.setMinMaxSize(size, _timeLocator.minHeight, size, _timeLocator.maxHeight);
	}

	function onSizeModified(w, h) {
		invalidateMaxWidth(_layerView.maxWidth);
		super.onSizeModified(w, h);
	}

	// レイヤビューのスクロール状況を監視
	function onLayerViewModified(childViewLeft, childViewTop, childViewWidth, childViewHeight, childWidth, childHeight) {
		_layerListScroll.setChildViewPos(_layerListScroll.childViewLeft, childViewTop);
		if (! _timeLocator.mouseDragScrollInterp.running)
			_timeLocatorScroll.setChildViewPos(childViewLeft, _timeLocatorScroll.childViewTop);
	}

	// レイヤリストのスクロール状況を監視
	function onLayerListModified(childViewLeft, childViewTop, childViewWidth, childViewHeight, childWidth, childHeight) {
		_layerViewScroll.setChildViewPos(_layerViewScroll.childViewLeft, childViewTop);
	}

	// レイヤリストの再描画を監視
	function onListModified {
		_layerView.setMinMaxSize(_layerView.minWidth, _layerList.minHeight,
								 _layerView.maxWidth, _layerList.maxHeight);
		_layerView.redrawAll();
		_layerViewScroll.setChildViewPos(_layerViewScroll.childViewLeft, _layerListScroll.childViewTop);
		resetCursor();
		resetSelection();
		resetArea();
		onLayerSelect(selectedLayer);
		onRenderFrame();
		invalidateMaxTime();
	}

	function onListRelocate {
		_layerView.setMinMaxSize(_layerView.minWidth, _layerList.minHeight,
								 _layerView.maxWidth, _layerList.maxHeight);
		_layerView.redrawAll();
		_layerViewScroll.setChildViewPos(_layerViewScroll.childViewLeft, _layerListScroll.childViewTop);
	}

	// レイヤリストの選択アイテム変更を監視
	function onListSelect {
		resetCursor();
//		resetSelection();
		onLayerSelect(selectedLayer);
		onRenderFrame();
	}

	function resetCursor {
		updateCursor();
	}

	function updateCursor {
		_layerView.updateCursor();
		_timeLocator.updateCursor();
	}

	// 選択範囲の設定をリセットする
	function resetSelection {
		var drawItemList = _layerList.drawItemList;
		for (var i = 0; i < drawItemList.count; i++) {
			if (drawItemList[i] isvalid)
				drawItemList[i].releaseSelection();
		}
		_layerView.onSelectionModified();
	}

	function resetArea {
		_layerView.resetArea();
	}

	property TIMELINE_FRAME_WIDTH {
		getter {
			return _frameWidth;
		}
	}

	property viewWidth {
		getter {
			return _viewWidth;
		}
		setter (v) {
			v = int(v);
			if (_viewWidth == v)
				return;
			_viewWidth = v;
			_viewWidthButton.label = TIMELINE_FRAME_WIDTH_LABEL_LIST[v];
			frameWidth = TIMELINE_FRAME_WIDTH_LIST[_viewWidth];
//			frameWidthDispatcher.interpolate(TIMELINE_FRAME_WIDTH_LIST[_viewWidth], 1000);
		}
	}

	property frameWidth {
		getter {
			return _frameWidth;
		}
		setter (v) {
			if (v == _frameWidth)
				return;
			var time = _layerViewScroll.horizontalBar.targetPos  / _frameWidth;
			_frameWidth = v;
			var pos = time * _frameWidth;
			invalidateMaxTime();
			_layerViewScroll.setChildViewPos(int(pos), _layerViewScroll.verticalBar.targetPos);
			_timeLocator.redrawAll();
			_layerView.onUpdateFrameWidth();
			_layerView.redrawAll();
			updateCursor();
		}
	}

	function onViewWidthChange {
		var menu = new KContextMenu(window);
		for (var i = 0; i < TIMELINE_FRAME_WIDTH_LABEL_LIST.count; i++)
			menu.addRadioItem(TIMELINE_FRAME_WIDTH_LABEL_LIST[i], i, "viewWidth", true, this.onViewWidthDecide);
		menu.viewWidth.value = viewWidth;
		menu.show();
	}

	function onViewWidthDecide(value) {
		viewWidth = value;
	}

	function onSearchNextFocusable(layer) {
		searchTarget = layer;
	}

	function onSearchPrevFocusable(layer) {
		searchTarget = layer;
	}

	function findLoopItem(itemList) {
		for (var i = 0; i < itemList.count; i++) {
			var item = itemList[i];
			if (item instanceof "KTimeLineLoopItem")
				return item;
			if (item.childList.count) {
				var result = findLoopItem(item.childList);
				if (result  !== void)
					return result;
			}
		}
		return void;
	}

	property loopItem {
		getter {
			return findLoopItem(_layerList.childList);
		}
	}

	property loopBeginTime {
		getter {
			var item = loopItem;
			if (item == void)
				return _loopBeginTime;
			else
				return item.loopBeginTime;
		}
		setter(v) {
			var item = loopItem;
			if (item !== void) {
				item.loopBeginTime = v;
				return;
			}
			_lastTime = -1;
			_loopBeginTime = v;
			if (_loopBeginTime == -1)
				_loopEndTime = -1;
			else if ( _loopBeginTime >= _loopEndTime)
				_loopEndTime = _loopBeginTime + 1;
		}
	}

	property loopEndTime {
		getter {
			var item = loopItem;
			if (item == void)
				return _loopEndTime;
			else
				return item.loopEndTime;
		}
		setter(v) {
			var item = loopItem;
			if (item !== void) {
				item.loopEndTime = v;
				return;
			}
			if (v == 0)
				v = 1;
			_lastTime = -1;
			_loopEndTime = v;
			if (_loopEndTime == -1)
				_loopBeginTime = -1;
			else if (_loopBeginTime == -1)
				_loopBeginTime = 0;
			else if (_loopBeginTime >= _loopEndTime)
				_loopBeginTime = _loopEndTime - 1;
		}
	}

	function setLoopTime(beginTime, endTime) {
		var item = loopItem;
		if (item !== void) {
			item.setLoopTime(beginTime, endTime);
		} else {
			_lastTime = -1;
			_loopBeginTime = beginTime;
			_loopEndTime = endTime;
		}
	}

	/**------------------------------
	 * 全アイテムの内、フレームの存在する最大の時間を返す
	 *
	 * @param v 最終時間(-1を設定するとリセット)
	 * @return 時間
	 ------------------------------*/
	property lastTime {
		setter(v) {
			var item = loopItem;
			if (item !== void)
				item.primaryLastTime = v;
			else {
				_lastTime = v;
				_loopBeginTime = -1;
				_loopEndTime = -1;
			}
		}
		getter {
			var item = loopItem;
			if (item !== void
				&& item.primaryLastTime != -1)
				return item.primaryLastTime;
			if (item === void
				&& _lastTime != -1)
				return _lastTime;
			var result = -1;
			var items = _layerList.descendants;
			for (var i = 0; i < items.count; i++)
				result = Math.max(result, items[i].lastTime);
			return int(result);
		}
	}



	function setActiveRange(begin, end) {
		_timeLocator.setActiveRange(begin, end);
	}

	property activeRangeEnabled {
		getter {
			return _timeLocator.activeRangeEnabled;
		}
		setter (v) {
			_timeLocator.activeRangeEnabled = v;
		}
	}

	property activeRangeBegin {
		getter {
			return _timeLocator.activeRangeBegin;
		}
		setter (v) {
			_timeLocator.activeRangeBegin = v;
		}
	}

	property activeRangeEnd {
		getter {
			return _timeLocator.activeRangeEnd;
		}
		setter (v) {
			_timeLocator.activeRangeEnd = v;
		}
	}

	function onBeginLabelEdit {
	}
	function onFinishLabelEdit {
	}

	function selectAll {
		_layerView.selectAll();
		_layerView.onSelectionModified();
	}

	property editable {
		getter {
			return _editable;
		}
		setter(v) {
			_editable = v;
			_layerList.enabled = v;
			_layerView.enabled = v;
		}
	}

	property multipleSelection {
		getter {
			return _layerList.multipleSelection;
		}

		setter(v) {
			_layerList.multipleSelection = v;
		}
	}

	property isCopyFramesAvailable {
		getter {
			return view.isCopyFramesAvailable;
		}
	}

	function copyFrames {
		return view.copyFrames();
	}

	function cutFrames {
		return view.cutFrames();
	}

	function isPasteFramesAvailable(rows, baseLayer = selectedLayer, baseTime = selectedTime) {
		return view.isPasteFramesAvailable(...);
	}

	function pasteFrames(rows, baseLayer = selectedLayer, baseTime = selectedTime) {
		view.pasteFrames(...);
	}

	function expandFrames(stride) {
		view.expandFrames(stride);
	}

	function shrinkFrames(stride) {
		view.shrinkFrames(stride);
	}

	function extendListSelectionToView {
		if (hasArea)
			resetArea();

		list.drawItemList.each(function(item) {
			if (! item.supportSelection
				|| ! item.selected)
				return;
			item.selectAllFrames();
		});
	}

	function onSinglePoint {
	}

	function onDrawView() {
	}

	function beginListSelection() {
		if (! extendListSelectionFromView)
			return;
		if (! multipleSelection)
			return;

		list.drawItemList.each(function(item) { item.prevSelected = item.selected; });
	}

	function resetListSelection() {
		list.drawItemList.each(function(item) { item.selected = item.prevSelected; });
	}

	function extendListSelection() {
		if (! extendListSelectionFromView)
			return;
		if (! multipleSelection)
			return;

		if (hasArea) {
			extendListSelectionByArea();
			return;
		}

		if (view.rangeSelectorActive) {
			extendListSelectionBySelection();
			return;
		}
	}

	function extendListSelectionByArea() {
		var indexRect = view.areaIndexRect;
		for (var i = 0; i < drawItemList.count; i++) {
			var item = drawItemList[i];
			if (item.supportSelection
				&& indexRect.top <= i
				&& i < indexRect.bottom)
				item.selected = true;
			else
				item.selected = false;
		}
	}

	function extendListSelectionBySelection() {
		var indexRect = view.rangeSelectorIndexRect;
		for (var i = 0; i < drawItemList.count; i++) {
			var item = drawItemList[i];
			var newlySelected = item.supportSelection
				&& indexRect.top <= i
				&& i <= indexRect.bottom;
			switch (view.rangeSelectMode) {
			case view.RANGE_SELECT_SET:
				item.selected = newlySelected;
				break;
			case view.RANGE_SELECT_ADD:
				item.selected = item.prevSelected || newlySelected;
				break;
			case view.RANGE_SELECT_FLIP:
				item.selected = (item.prevSelected ^ newlySelected) || item.hasSelection;
				break;
			}
		}
	}

	property selectionModeRangeEnabled {
		getter {
			return (selectionModeMask & TIMELINE_SELECTION_MODE_MASK_RANGE) != 0;
		}
	}

	property selectionModeFrameEnabled {
		getter {
			return (selectionModeMask & TIMELINE_SELECTION_MODE_MASK_FRAME) != 0;
		}
	}

	property keyframePriorSideLeft {
		getter {
			return keyframePriorSide == TIMELINE_KEYFRAME_PRIOR_SIDE_LEFT;
		}
	}

	property keyframePriorSideRight {
		getter {
			return keyframePriorSide == TIMELINE_KEYFRAME_PRIOR_SIDE_RIGHT;
		}
	}

};
